version: "3.8"
services:
  change_engine:
    build:
      context: .
      args:
        # get from shell command
        # https://stackoverflow.com/a/48998148
        IASQL_ENV: |-
          ${IASQL_ENV}
    ports:
      - "8088:8088"
    links:
      - postgresql
  postgresql:
    image: postgres:14.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
