version: "3.8"
services:
  change_engine:
    build:
      context: .
      args:
        # get from shell command
        # https://stackoverflow.com/a/48998148
        IASQL_ENV: |-
          ${IASQL_ENV}
    ports:
      - "8088:8088"
    links:
      - postgresql
  postgresql:
    build:
      dockerfile: Dockerfile.pg
      context: .
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=iasql_metadata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
