version: "3.8"
services:
  change_engine:
    build: .
    ports:
      - "8088:8088"
    links:
      - postgresql
    environment:
      - PORT=8088
    env_file:
      - .env
  postgresql:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
