# Generated by Django 3.2.12 on 2022-03-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            """
            SELECT * FROM iasql_install(
                'aws_vpc',
                'aws_security_group',
                'aws_elb',
                'aws_cloudwatch',
                'aws_ecr',
                'aws_ecs_fargate',
                'aws_rds',
                'aws_iam'
            );
            """,
            """
            SELECT * FROM iasql_uninstall(
                'aws_vpc',
                'aws_security_group',
                'aws_elb',
                'aws_cloudwatch',
                'aws_ecr',
                'aws_ecs_fargate',
                'aws_rds',
                'aws_iam'
            );
            """
        )
    ]
