# Generated by Django 3.2.12 on 2022-04-08 11:44

from django.conf import settings
from django.db import migrations, connections

from infra.models import EcsSimplified

# TODO replace with your desired project name
PROJECT_NAME = settings.IASQL_PROJECT_NAME

PORT = 8088


def quickstart_up(_apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ecs_deployment, _ = EcsSimplified.objects.using(db_alias).get_or_create(
        app_name=PROJECT_NAME,
        public_ip=True,
        app_port=PORT,
        image_tag='latest',
        cpu_mem='vCPU2-8GB',
        desired_count=1
    )


def quickstart_down(_apps, schema_editor):
    db_alias = schema_editor.connection.alias

    EcsSimplified.objects.using(db_alias).filter(
        app_name=PROJECT_NAME,
        app_port=PORT,
    ).delete()


def apply(_, schema_editor):
    db_alias = schema_editor.connection.alias
    with connections[db_alias].cursor() as cursor:
        cursor.callproc('iasql_commit')
        columns = [col[0] for col in cursor.description]
        print("\n")
        print([
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('infra', '0002_inspectdb'),
    ]

    operations = [
        migrations.RunPython(code=quickstart_up, reverse_code=apply, atomic=True),
        migrations.RunPython(code=apply, reverse_code=quickstart_down, atomic=True),
    ]
