ALTER DEFAULT PRIVILEGES
FOR USER CURRENT_USER
IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO PUBLIC;

ALTER DEFAULT PRIVILEGES
FOR USER CURRENT_USER
IN SCHEMA public
GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES
FOR USER CURRENT_USER
IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO PUBLIC;

GRANT SELECT ON iasql_module, iasql_tables, iasql_audit_log TO PUBLIC;
