import * as iasql from '../../src/services/iasql'
import { getPrefix, runQuery, runApply, finish, execComposeUp, execComposeDown, } from '../helpers'

jest.setTimeout(240000);

beforeAll(execComposeUp);

afterAll(execComposeDown);

const prefix = getPrefix();
const dbAlias = 'cwtest';
const logGroupName = `${prefix}lgtest`
const apply = runApply.bind(null, dbAlias);
const query = runQuery.bind(null, dbAlias);

describe('AwsCloudwatch Integration Testing', () => {
  it('creates a new test db', (done) => void iasql.add(
    dbAlias,
    'us-west-2',
    process.env.AWS_ACCESS_KEY_ID ?? 'barf',
    process.env.AWS_SECRET_ACCESS_KEY ?? 'barf',
    'not-needed').then(...finish(done)));

  it('installs the cloudwatch module', (done) => void iasql.install(
    ['aws_cloudwatch@0.0.1'],
    dbAlias,
    'not-needed').then(...finish(done)));

  it('adds a new log group', query(`
    INSERT INTO log_group (log_group_name)
    VALUES ('${logGroupName}');
  `));

  it('applies the log group change', apply);


  it('tries to update a log group autogenerated field', query(`
    UPDATE log_group SET log_group_arn = '${logGroupName}2' WHERE log_group_name = '${logGroupName}';
  `));

  it('applies the log group change which will undo the change', apply);

  it('deletes the log group', query(`
    DELETE FROM log_group
    WHERE log_group_name = '${logGroupName}';
  `));

  it('applies the log group change (last time)', apply);

  it('deletes the test db', (done) => void iasql
    .remove(dbAlias, 'not-needed')
    .then(...finish(done)));
});

describe('AwsCloudwatch Integration Testing SP', () => {
  it('creates a new test db', (done) => void iasql.add(
    dbAlias,
    'us-west-2',
    process.env.AWS_ACCESS_KEY_ID ?? 'barf',
    process.env.AWS_SECRET_ACCESS_KEY ?? 'barf',
    'not-needed').then(...finish(done)));

  it('installs the cloudwatch module', (done) => void iasql.install(
    ['aws_cloudwatch@0.0.1'],
    dbAlias,
    'not-needed').then(...finish(done)));

  it('adds a new log group', query(`
    call create_or_update_cloudwatch_log_group('${logGroupName}');
  `));

  it('check number of instances', query(`
    SELECT *
    FROM log_group
    WHERE log_group_name = '${logGroupName}';
  `, (res: any[]) => expect(res.length).toBe(1)));

  it('applies adds a new log group', apply);

  it('deletes the log group', query(`
    call delete_cloudwatch_log_group('${logGroupName}');
  `));

  it('check number of instances', query(`
    SELECT *
    FROM log_group
    WHERE log_group_name = '${logGroupName}';
  `, (res: any[]) => expect(res.length).toBe(0)));

  it('applies deletes the log group', apply);

  it('deletes the test db', (done) => void iasql
    .remove(dbAlias, 'not-needed')
    .then(...finish(done)));
});
