import {MigrationInterface, QueryRunner} from "typeorm";

export class instanceType1632287020184 implements MigrationInterface {
    name = 'instanceType1632287020184'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "boot_mode" ("id" SERIAL NOT NULL, "mode" character varying NOT NULL, CONSTRAINT "PK_114728d4fa02f297923c52ae1e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cpu_architecture" ("id" SERIAL NOT NULL, "cpuArchitecture" character varying NOT NULL, CONSTRAINT "UQ_4bc685244b74099f073c42ad735" UNIQUE ("cpuArchitecture"), CONSTRAINT "PK_4374571b2fdb60c03e8876a5059" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "device_type" ("id" SERIAL NOT NULL, "deviceType" character varying NOT NULL, CONSTRAINT "UQ_e7709b043396305fcfb252a1972" UNIQUE ("deviceType"), CONSTRAINT "PK_f8d1c0daa8abde339c1056535a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "disk_info_type_enum" AS ENUM('hdd', 'ssd')`);
        await queryRunner.query(`CREATE TABLE "disk_info" ("id" SERIAL NOT NULL, "sizeInGB" numeric NOT NULL, "count" integer NOT NULL, "type" "disk_info_type_enum" NOT NULL, CONSTRAINT "PK_a145ea93c1809aa3ab0eaa8c0c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ebs_optimized_info" ("id" SERIAL NOT NULL, "baselineBandwidthInMbps" numeric NOT NULL, "baselineThroughputInMBps" numeric NOT NULL, "baselineIOPS" numeric NOT NULL, "maximumBandwidthInMbps" numeric NOT NULL, "maximumThroughputInMBps" numeric NOT NULL, "maximumIOPS" numeric NOT NULL, CONSTRAINT "PK_b30c043be425c0015e97bc91c80" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "instance_storage_info_nvmesupport_enum" AS ENUM('required', 'supported', 'unsupported')`);
        await queryRunner.query(`CREATE TABLE "instance_storage_info" ("id" SERIAL NOT NULL, "totalSizeInGB" numeric NOT NULL, "NVMESupport" "instance_storage_info_nvmesupport_enum" NOT NULL, CONSTRAINT "PK_7a8c50e616d5415a68253bddf47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "ebs_info_ebsoptimizedsupport_enum" AS ENUM('default', 'supported', 'unsupported')`);
        await queryRunner.query(`CREATE TYPE "ebs_info_encryptionsupport_enum" AS ENUM('supported', 'unsupported')`);
        await queryRunner.query(`CREATE TYPE "ebs_info_nvmesupport_enum" AS ENUM('required', 'supported', 'unsupported')`);
        await queryRunner.query(`CREATE TABLE "ebs_info" ("id" SERIAL NOT NULL, "ebsOptimizedSupport" "ebs_info_ebsoptimizedsupport_enum" NOT NULL, "encryptionSupport" "ebs_info_encryptionsupport_enum" NOT NULL, "NVMESupport" "ebs_info_nvmesupport_enum" NOT NULL, "ebs_optimized_info_id" integer, CONSTRAINT "REL_c0d05e1ff186d9c4d26ed747d0" UNIQUE ("ebs_optimized_info_id"), CONSTRAINT "PK_9012f4f7e784c479f53e0f195f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "efa_info" ("id" SERIAL NOT NULL, "maximumEFAInterfaces" integer NOT NULL, CONSTRAINT "PK_4f369baf517168abda55b75180d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fpga_device_memory_info" ("id" SERIAL NOT NULL, "sizeInMiB" numeric NOT NULL, CONSTRAINT "PK_54bbcc5b13a900209e1e5ee1cf7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fpga_device_info" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "manufacturer" character varying NOT NULL, "count" integer NOT NULL, "fpga_device_memory_info_id" integer, CONSTRAINT "PK_6d50c7a37c3b72c0c9ff98b2369" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fpga_info" ("id" SERIAL NOT NULL, "totalFPGAMemoryInMiB" numeric NOT NULL, CONSTRAINT "PK_2d6188cbef48d727e6c3e9675c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gpu_device_memory_info" ("id" SERIAL NOT NULL, "sizeInMiB" numeric NOT NULL, CONSTRAINT "PK_5832252cad6df9e5981ff55e6d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gpu_device_info" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "manufacturer" character varying NOT NULL, "count" integer NOT NULL, "gpu_device_memory_info_id" integer, CONSTRAINT "PK_900d565d2815aec5823dfc6d28c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gpu_info" ("id" SERIAL NOT NULL, "totalGPUMemoryInMiB" numeric NOT NULL, CONSTRAINT "PK_b1f6c1b4319c4c09341f425dcf3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inference_device_info" ("id" SERIAL NOT NULL, "count" integer NOT NULL, "name" character varying NOT NULL, "manufacturer" character varying NOT NULL, CONSTRAINT "PK_fa829b22aa5feefb03fab5fbae9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inference_accelerator_info" ("id" SERIAL NOT NULL, CONSTRAINT "PK_67ef5a210c7303d30e4a5e14eae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "network_card_info" ("id" SERIAL NOT NULL, "networkCardIndex" integer NOT NULL, "networkPerformance" character varying NOT NULL, "maximumNetworkInterfaces" integer NOT NULL, CONSTRAINT "PK_5ba7818deb23194370050a59df1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "network_info_enasupport_enum" AS ENUM('required', 'supported', 'unsupported')`);
        await queryRunner.query(`CREATE TABLE "network_info" ("id" SERIAL NOT NULL, "networkPerformance" character varying NOT NULL, "maximumNetworkInterfaces" integer NOT NULL, "maximumNetworkCards" integer NOT NULL, "defaultNetworkCardIndex" integer NOT NULL, "ipv4AddressesPerInterface" integer NOT NULL, "ipv6AddressesPerInterface" integer NOT NULL, "ipv6Supported" boolean NOT NULL, "enaSupport" "network_info_enasupport_enum" NOT NULL, "efaSupported" boolean NOT NULL, "encryptionInTransitSupported" boolean NOT NULL, "efa_info_id" integer, CONSTRAINT "REL_5abc0ca3d03456246a6d1eacc8" UNIQUE ("efa_info_id"), CONSTRAINT "PK_81214b7c50e1372b56fa9db1139" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "placement_group_strategy" ("id" SERIAL NOT NULL, "strategy" character varying NOT NULL, CONSTRAINT "UQ_a34a971173d06144038dea8b028" UNIQUE ("strategy"), CONSTRAINT "PK_10966ef9356db3e3a9f95561603" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "placement_group_info" ("id" SERIAL NOT NULL, CONSTRAINT "PK_a01f2095ad16d54d185a1173790" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "processor_info" ("id" SERIAL NOT NULL, "sustainedClockSpeedInGHz" numeric NOT NULL, CONSTRAINT "PK_d49b0841d52bfff06c9556daf6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usage_class" ("id" SERIAL NOT NULL, "usageClass" character varying NOT NULL, CONSTRAINT "UQ_6c0d453f3dda037c94190ff4ef6" UNIQUE ("usageClass"), CONSTRAINT "PK_0c1f22f9333c84614dee14ec5b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "valid_core" ("id" SERIAL NOT NULL, "count" integer NOT NULL, CONSTRAINT "PK_0c78fcb17fc566b89f272a4ed30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "valid_threads_per_core" ("id" SERIAL NOT NULL, "count" integer NOT NULL, CONSTRAINT "PK_51de13a0622b9a87423a7e9f242" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vcpu_info" ("id" SERIAL NOT NULL, "defaultVCPUs" integer NOT NULL, "defaultCores" integer NOT NULL, "defaultThreadsPerCore" integer NOT NULL, CONSTRAINT "PK_124ca200f80f5ae0c9af443427a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "virtualization_type" ("id" SERIAL NOT NULL, "virtualizationType" character varying NOT NULL, CONSTRAINT "UQ_181f2e7a0b47a335442cc945df2" UNIQUE ("virtualizationType"), CONSTRAINT "PK_d798c8354c1647240be159f6f56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "instance_type_instancetype_enum" AS ENUM('a1.2xlarge', 'a1.4xlarge', 'a1.large', 'a1.medium', 'a1.metal', 'a1.xlarge', 'c1.medium', 'c1.xlarge', 'c3.2xlarge', 'c3.4xlarge', 'c3.8xlarge', 'c3.large', 'c3.xlarge', 'c4.2xlarge', 'c4.4xlarge', 'c4.8xlarge', 'c4.large', 'c4.xlarge', 'c5.12xlarge', 'c5.18xlarge', 'c5.24xlarge', 'c5.2xlarge', 'c5.4xlarge', 'c5.9xlarge', 'c5.large', 'c5.metal', 'c5.xlarge', 'c5a.12xlarge', 'c5a.16xlarge', 'c5a.24xlarge', 'c5a.2xlarge', 'c5a.4xlarge', 'c5a.8xlarge', 'c5a.large', 'c5a.xlarge', 'c5ad.12xlarge', 'c5ad.16xlarge', 'c5ad.24xlarge', 'c5ad.2xlarge', 'c5ad.4xlarge', 'c5ad.8xlarge', 'c5ad.large', 'c5ad.xlarge', 'c5d.12xlarge', 'c5d.18xlarge', 'c5d.24xlarge', 'c5d.2xlarge', 'c5d.4xlarge', 'c5d.9xlarge', 'c5d.large', 'c5d.metal', 'c5d.xlarge', 'c5n.18xlarge', 'c5n.2xlarge', 'c5n.4xlarge', 'c5n.9xlarge', 'c5n.large', 'c5n.metal', 'c5n.xlarge', 'c6g.12xlarge', 'c6g.16xlarge', 'c6g.2xlarge', 'c6g.4xlarge', 'c6g.8xlarge', 'c6g.large', 'c6g.medium', 'c6g.metal', 'c6g.xlarge', 'c6gd.12xlarge', 'c6gd.16xlarge', 'c6gd.2xlarge', 'c6gd.4xlarge', 'c6gd.8xlarge', 'c6gd.large', 'c6gd.medium', 'c6gd.metal', 'c6gd.xlarge', 'c6gn.12xlarge', 'c6gn.16xlarge', 'c6gn.2xlarge', 'c6gn.4xlarge', 'c6gn.8xlarge', 'c6gn.large', 'c6gn.medium', 'c6gn.xlarge', 'cc1.4xlarge', 'cc2.8xlarge', 'cg1.4xlarge', 'cr1.8xlarge', 'd2.2xlarge', 'd2.4xlarge', 'd2.8xlarge', 'd2.xlarge', 'd3.2xlarge', 'd3.4xlarge', 'd3.8xlarge', 'd3.xlarge', 'd3en.12xlarge', 'd3en.2xlarge', 'd3en.4xlarge', 'd3en.6xlarge', 'd3en.8xlarge', 'd3en.xlarge', 'f1.16xlarge', 'f1.2xlarge', 'f1.4xlarge', 'g2.2xlarge', 'g2.8xlarge', 'g3.16xlarge', 'g3.4xlarge', 'g3.8xlarge', 'g3s.xlarge', 'g4ad.16xlarge', 'g4ad.2xlarge', 'g4ad.4xlarge', 'g4ad.8xlarge', 'g4ad.xlarge', 'g4dn.12xlarge', 'g4dn.16xlarge', 'g4dn.2xlarge', 'g4dn.4xlarge', 'g4dn.8xlarge', 'g4dn.metal', 'g4dn.xlarge', 'h1.16xlarge', 'h1.2xlarge', 'h1.4xlarge', 'h1.8xlarge', 'hi1.4xlarge', 'hs1.8xlarge', 'i2.2xlarge', 'i2.4xlarge', 'i2.8xlarge', 'i2.xlarge', 'i3.16xlarge', 'i3.2xlarge', 'i3.4xlarge', 'i3.8xlarge', 'i3.large', 'i3.metal', 'i3.xlarge', 'i3en.12xlarge', 'i3en.24xlarge', 'i3en.2xlarge', 'i3en.3xlarge', 'i3en.6xlarge', 'i3en.large', 'i3en.metal', 'i3en.xlarge', 'inf1.24xlarge', 'inf1.2xlarge', 'inf1.6xlarge', 'inf1.xlarge', 'm1.large', 'm1.medium', 'm1.small', 'm1.xlarge', 'm2.2xlarge', 'm2.4xlarge', 'm2.xlarge', 'm3.2xlarge', 'm3.large', 'm3.medium', 'm3.xlarge', 'm4.10xlarge', 'm4.16xlarge', 'm4.2xlarge', 'm4.4xlarge', 'm4.large', 'm4.xlarge', 'm5.12xlarge', 'm5.16xlarge', 'm5.24xlarge', 'm5.2xlarge', 'm5.4xlarge', 'm5.8xlarge', 'm5.large', 'm5.metal', 'm5.xlarge', 'm5a.12xlarge', 'm5a.16xlarge', 'm5a.24xlarge', 'm5a.2xlarge', 'm5a.4xlarge', 'm5a.8xlarge', 'm5a.large', 'm5a.xlarge', 'm5ad.12xlarge', 'm5ad.16xlarge', 'm5ad.24xlarge', 'm5ad.2xlarge', 'm5ad.4xlarge', 'm5ad.8xlarge', 'm5ad.large', 'm5ad.xlarge', 'm5d.12xlarge', 'm5d.16xlarge', 'm5d.24xlarge', 'm5d.2xlarge', 'm5d.4xlarge', 'm5d.8xlarge', 'm5d.large', 'm5d.metal', 'm5d.xlarge', 'm5dn.12xlarge', 'm5dn.16xlarge', 'm5dn.24xlarge', 'm5dn.2xlarge', 'm5dn.4xlarge', 'm5dn.8xlarge', 'm5dn.large', 'm5dn.metal', 'm5dn.xlarge', 'm5n.12xlarge', 'm5n.16xlarge', 'm5n.24xlarge', 'm5n.2xlarge', 'm5n.4xlarge', 'm5n.8xlarge', 'm5n.large', 'm5n.metal', 'm5n.xlarge', 'm5zn.12xlarge', 'm5zn.2xlarge', 'm5zn.3xlarge', 'm5zn.6xlarge', 'm5zn.large', 'm5zn.metal', 'm5zn.xlarge', 'm6g.12xlarge', 'm6g.16xlarge', 'm6g.2xlarge', 'm6g.4xlarge', 'm6g.8xlarge', 'm6g.large', 'm6g.medium', 'm6g.metal', 'm6g.xlarge', 'm6gd.12xlarge', 'm6gd.16xlarge', 'm6gd.2xlarge', 'm6gd.4xlarge', 'm6gd.8xlarge', 'm6gd.large', 'm6gd.medium', 'm6gd.metal', 'm6gd.xlarge', 'm6i.12xlarge', 'm6i.16xlarge', 'm6i.24xlarge', 'm6i.2xlarge', 'm6i.32xlarge', 'm6i.4xlarge', 'm6i.8xlarge', 'm6i.large', 'm6i.xlarge', 'mac1.metal', 'p2.16xlarge', 'p2.8xlarge', 'p2.xlarge', 'p3.16xlarge', 'p3.2xlarge', 'p3.8xlarge', 'p3dn.24xlarge', 'p4d.24xlarge', 'r3.2xlarge', 'r3.4xlarge', 'r3.8xlarge', 'r3.large', 'r3.xlarge', 'r4.16xlarge', 'r4.2xlarge', 'r4.4xlarge', 'r4.8xlarge', 'r4.large', 'r4.xlarge', 'r5.12xlarge', 'r5.16xlarge', 'r5.24xlarge', 'r5.2xlarge', 'r5.4xlarge', 'r5.8xlarge', 'r5.large', 'r5.metal', 'r5.xlarge', 'r5a.12xlarge', 'r5a.16xlarge', 'r5a.24xlarge', 'r5a.2xlarge', 'r5a.4xlarge', 'r5a.8xlarge', 'r5a.large', 'r5a.xlarge', 'r5ad.12xlarge', 'r5ad.16xlarge', 'r5ad.24xlarge', 'r5ad.2xlarge', 'r5ad.4xlarge', 'r5ad.8xlarge', 'r5ad.large', 'r5ad.xlarge', 'r5b.12xlarge', 'r5b.16xlarge', 'r5b.24xlarge', 'r5b.2xlarge', 'r5b.4xlarge', 'r5b.8xlarge', 'r5b.large', 'r5b.metal', 'r5b.xlarge', 'r5d.12xlarge', 'r5d.16xlarge', 'r5d.24xlarge', 'r5d.2xlarge', 'r5d.4xlarge', 'r5d.8xlarge', 'r5d.large', 'r5d.metal', 'r5d.xlarge', 'r5dn.12xlarge', 'r5dn.16xlarge', 'r5dn.24xlarge', 'r5dn.2xlarge', 'r5dn.4xlarge', 'r5dn.8xlarge', 'r5dn.large', 'r5dn.metal', 'r5dn.xlarge', 'r5n.12xlarge', 'r5n.16xlarge', 'r5n.24xlarge', 'r5n.2xlarge', 'r5n.4xlarge', 'r5n.8xlarge', 'r5n.large', 'r5n.metal', 'r5n.xlarge', 'r6g.12xlarge', 'r6g.16xlarge', 'r6g.2xlarge', 'r6g.4xlarge', 'r6g.8xlarge', 'r6g.large', 'r6g.medium', 'r6g.metal', 'r6g.xlarge', 'r6gd.12xlarge', 'r6gd.16xlarge', 'r6gd.2xlarge', 'r6gd.4xlarge', 'r6gd.8xlarge', 'r6gd.large', 'r6gd.medium', 'r6gd.metal', 'r6gd.xlarge', 't1.micro', 't2.2xlarge', 't2.large', 't2.medium', 't2.micro', 't2.nano', 't2.small', 't2.xlarge', 't3.2xlarge', 't3.large', 't3.medium', 't3.micro', 't3.nano', 't3.small', 't3.xlarge', 't3a.2xlarge', 't3a.large', 't3a.medium', 't3a.micro', 't3a.nano', 't3a.small', 't3a.xlarge', 't4g.2xlarge', 't4g.large', 't4g.medium', 't4g.micro', 't4g.nano', 't4g.small', 't4g.xlarge', 'u-12tb1.112xlarge', 'u-12tb1.metal', 'u-18tb1.metal', 'u-24tb1.metal', 'u-6tb1.112xlarge', 'u-6tb1.56xlarge', 'u-6tb1.metal', 'u-9tb1.112xlarge', 'u-9tb1.metal', 'x1.16xlarge', 'x1.32xlarge', 'x1e.16xlarge', 'x1e.2xlarge', 'x1e.32xlarge', 'x1e.4xlarge', 'x1e.8xlarge', 'x1e.xlarge', 'x2gd.12xlarge', 'x2gd.16xlarge', 'x2gd.2xlarge', 'x2gd.4xlarge', 'x2gd.8xlarge', 'x2gd.large', 'x2gd.medium', 'x2gd.metal', 'x2gd.xlarge', 'z1d.12xlarge', 'z1d.2xlarge', 'z1d.3xlarge', 'z1d.6xlarge', 'z1d.large', 'z1d.metal', 'z1d.xlarge')`);
        await queryRunner.query(`CREATE TYPE "instance_type_hypervisor_enum" AS ENUM('nitro', 'xen')`);
        await queryRunner.query(`CREATE TABLE "instance_type" ("id" SERIAL NOT NULL, "instanceType" "instance_type_instancetype_enum" NOT NULL, "currentGeneration" boolean NOT NULL, "freeTierEligible" boolean NOT NULL, "bareMetal" boolean NOT NULL, "hypervisor" "instance_type_hypervisor_enum" NOT NULL, "memorySizeInMiB" numeric NOT NULL, "instanceStorageSupported" boolean NOT NULL, "hibernationSupported" boolean NOT NULL, "burstablePerformanceSupported" boolean NOT NULL, "dedicatedHostsSupported" boolean NOT NULL, "autoRecoverySupported" boolean NOT NULL, "processor_info_id" integer, "v_cpu_info_id" integer, "instance_storage_info_id" integer, "ebs_info_id" integer, "network_info_id" integer, "gpu_info_id" integer, "fpga_info_id" integer, "placement_group_info_id" integer, "inference_accelerator_info_id" integer, CONSTRAINT "PK_2ff067127c52f0f23049642883a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "instance_storage_info_disks_disk_info" ("instanceStorageInfoId" integer NOT NULL, "diskInfoId" integer NOT NULL, CONSTRAINT "PK_c6192c7134ac83bca4a6252347e" PRIMARY KEY ("instanceStorageInfoId", "diskInfoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b12a15c05cc37e279554f5ce7" ON "instance_storage_info_disks_disk_info" ("instanceStorageInfoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f26504b23aa1d0966aedaefa80" ON "instance_storage_info_disks_disk_info" ("diskInfoId") `);
        await queryRunner.query(`CREATE TABLE "fpga_info_fpgas_fpga_device_info" ("fpgaInfoId" integer NOT NULL, "fpgaDeviceInfoId" integer NOT NULL, CONSTRAINT "PK_9ac3610d2862b2d49a97c550ad9" PRIMARY KEY ("fpgaInfoId", "fpgaDeviceInfoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_efc682159731f5f8bd2b776ab6" ON "fpga_info_fpgas_fpga_device_info" ("fpgaInfoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1a740c375af691f8fd47908cf" ON "fpga_info_fpgas_fpga_device_info" ("fpgaDeviceInfoId") `);
        await queryRunner.query(`CREATE TABLE "gpu_info_gpus_gpu_device_info" ("gpuInfoId" integer NOT NULL, "gpuDeviceInfoId" integer NOT NULL, CONSTRAINT "PK_a23133f581833ea97180c0ed4e9" PRIMARY KEY ("gpuInfoId", "gpuDeviceInfoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71b952e068cb2458c680b0ea73" ON "gpu_info_gpus_gpu_device_info" ("gpuInfoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b8582e2b009b8c08e972e9525" ON "gpu_info_gpus_gpu_device_info" ("gpuDeviceInfoId") `);
        await queryRunner.query(`CREATE TABLE "inference_accelerator_info_accelerators_inference_device_info" ("inferenceAcceleratorInfoId" integer NOT NULL, "inferenceDeviceInfoId" integer NOT NULL, CONSTRAINT "PK_e19819ea40480a5492da8f87f4f" PRIMARY KEY ("inferenceAcceleratorInfoId", "inferenceDeviceInfoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a01d9a1f69047f90898bbc7548" ON "inference_accelerator_info_accelerators_inference_device_info" ("inferenceAcceleratorInfoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b822f14e8c5d226905e0a1373e" ON "inference_accelerator_info_accelerators_inference_device_info" ("inferenceDeviceInfoId") `);
        await queryRunner.query(`CREATE TABLE "network_info_network_cards_network_card_info" ("networkInfoId" integer NOT NULL, "networkCardInfoId" integer NOT NULL, CONSTRAINT "PK_0e1fe86a5451cb49891062f83ec" PRIMARY KEY ("networkInfoId", "networkCardInfoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38e3395028d80a8e5a422287db" ON "network_info_network_cards_network_card_info" ("networkInfoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c33046e851961c6f9a131aeb6" ON "network_info_network_cards_network_card_info" ("networkCardInfoId") `);
        await queryRunner.query(`CREATE TABLE "pla_gro_inf_sup_str_pla_gro_str" ("placementGroupInfoId" integer NOT NULL, "placementGroupStrategyId" integer NOT NULL, CONSTRAINT "PK_5aa3969c938d027fdfc7222bbff" PRIMARY KEY ("placementGroupInfoId", "placementGroupStrategyId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df2384ed345ea02b4605528778" ON "pla_gro_inf_sup_str_pla_gro_str" ("placementGroupInfoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9706401551c7ca9fa91d3f47b" ON "pla_gro_inf_sup_str_pla_gro_str" ("placementGroupStrategyId") `);
        await queryRunner.query(`CREATE TABLE "processor_info_supported_architectures_cpu_architecture" ("processorInfoId" integer NOT NULL, "cpuArchitectureId" integer NOT NULL, CONSTRAINT "PK_0b2cca4531082f0b9f1eaf29ad3" PRIMARY KEY ("processorInfoId", "cpuArchitectureId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_61c1342b3f5ea1eed2a925918b" ON "processor_info_supported_architectures_cpu_architecture" ("processorInfoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_528f6ad79fa40bed258063306f" ON "processor_info_supported_architectures_cpu_architecture" ("cpuArchitectureId") `);
        await queryRunner.query(`CREATE TABLE "vcpu_info_valid_cores_valid_core" ("vcpuInfoId" integer NOT NULL, "validCoreId" integer NOT NULL, CONSTRAINT "PK_11f0bc450e1429705338e1131a3" PRIMARY KEY ("vcpuInfoId", "validCoreId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7627cd35b944da31aa7b70f647" ON "vcpu_info_valid_cores_valid_core" ("vcpuInfoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6bfcecb8b3e69646c70f259cc7" ON "vcpu_info_valid_cores_valid_core" ("validCoreId") `);
        await queryRunner.query(`CREATE TABLE "vcpu_info_valid_threads_per_core_valid_threads_per_core" ("vcpuInfoId" integer NOT NULL, "validThreadsPerCoreId" integer NOT NULL, CONSTRAINT "PK_5a6cca75fc8bbadf1d058432345" PRIMARY KEY ("vcpuInfoId", "validThreadsPerCoreId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_19bde7851ddb55c88d9f83e6b5" ON "vcpu_info_valid_threads_per_core_valid_threads_per_core" ("vcpuInfoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac3a3f74934b0e90a077d2ab5d" ON "vcpu_info_valid_threads_per_core_valid_threads_per_core" ("validThreadsPerCoreId") `);
        await queryRunner.query(`CREATE TABLE "instance_type_supported_usage_classes_usage_class" ("instanceTypeId" integer NOT NULL, "usageClassId" integer NOT NULL, CONSTRAINT "PK_5352f60d5e6abb127f880ff48bc" PRIMARY KEY ("instanceTypeId", "usageClassId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee864286f0efb1f01030c9dc75" ON "instance_type_supported_usage_classes_usage_class" ("instanceTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1dad445b95c880dc668fd01ceb" ON "instance_type_supported_usage_classes_usage_class" ("usageClassId") `);
        await queryRunner.query(`CREATE TABLE "instance_type_supported_root_device_types_device_type" ("instanceTypeId" integer NOT NULL, "deviceTypeId" integer NOT NULL, CONSTRAINT "PK_05e7ecf05ab06569e23eb8793f2" PRIMARY KEY ("instanceTypeId", "deviceTypeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_912b11c90cb1561261c71cd5dc" ON "instance_type_supported_root_device_types_device_type" ("instanceTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd4dfa196aae7012c698788789" ON "instance_type_supported_root_device_types_device_type" ("deviceTypeId") `);
        await queryRunner.query(`CREATE TABLE "ins_typ_sup_vir_typ_vir_typ" ("instanceTypeId" integer NOT NULL, "virtualizationTypeId" integer NOT NULL, CONSTRAINT "PK_3ce588be477c139ddbbfca8ec44" PRIMARY KEY ("instanceTypeId", "virtualizationTypeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3882f8bb56e24d9ed43d1c4c24" ON "ins_typ_sup_vir_typ_vir_typ" ("instanceTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7db3c32e781541f328f0502fa" ON "ins_typ_sup_vir_typ_vir_typ" ("virtualizationTypeId") `);
        await queryRunner.query(`CREATE TABLE "instance_type_supported_boot_modes_boot_mode" ("instanceTypeId" integer NOT NULL, "bootModeId" integer NOT NULL, CONSTRAINT "PK_26f9380b908e7b57aaebdae947c" PRIMARY KEY ("instanceTypeId", "bootModeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_63d531a5057bf5bf18cac8a2f2" ON "instance_type_supported_boot_modes_boot_mode" ("instanceTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5e1e0258e6532899c373cf727" ON "instance_type_supported_boot_modes_boot_mode" ("bootModeId") `);
        await queryRunner.query(`ALTER TABLE "ebs_info" ADD CONSTRAINT "FK_c0d05e1ff186d9c4d26ed747d08" FOREIGN KEY ("ebs_optimized_info_id") REFERENCES "ebs_optimized_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fpga_device_info" ADD CONSTRAINT "FK_c83fc8695a42bc116e46db17bf6" FOREIGN KEY ("fpga_device_memory_info_id") REFERENCES "fpga_device_memory_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gpu_device_info" ADD CONSTRAINT "FK_175d0ad17acc9c353077ba5d4e3" FOREIGN KEY ("gpu_device_memory_info_id") REFERENCES "gpu_device_memory_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "network_info" ADD CONSTRAINT "FK_5abc0ca3d03456246a6d1eacc84" FOREIGN KEY ("efa_info_id") REFERENCES "efa_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_type" ADD CONSTRAINT "FK_837d9c5af92d3108647ba0f6190" FOREIGN KEY ("processor_info_id") REFERENCES "processor_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_type" ADD CONSTRAINT "FK_a82e73fc00bf3488ee9d93055a7" FOREIGN KEY ("v_cpu_info_id") REFERENCES "vcpu_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_type" ADD CONSTRAINT "FK_1867d2499134bd841f6dd932161" FOREIGN KEY ("instance_storage_info_id") REFERENCES "instance_storage_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_type" ADD CONSTRAINT "FK_c74fd39985596ee10d03b405759" FOREIGN KEY ("ebs_info_id") REFERENCES "ebs_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_type" ADD CONSTRAINT "FK_8a48290f7e48a213fe6b0931db6" FOREIGN KEY ("network_info_id") REFERENCES "network_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_type" ADD CONSTRAINT "FK_7348bb6aba22093bf045157cb55" FOREIGN KEY ("gpu_info_id") REFERENCES "gpu_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_type" ADD CONSTRAINT "FK_e9fd23c6b05997baa8f803f1c17" FOREIGN KEY ("fpga_info_id") REFERENCES "fpga_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_type" ADD CONSTRAINT "FK_acadb5566239d7fdbeeb0919729" FOREIGN KEY ("placement_group_info_id") REFERENCES "placement_group_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_type" ADD CONSTRAINT "FK_b906f76dd0f0a7a4613bdf4f043" FOREIGN KEY ("inference_accelerator_info_id") REFERENCES "inference_accelerator_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_storage_info_disks_disk_info" ADD CONSTRAINT "FK_2b12a15c05cc37e279554f5ce7c" FOREIGN KEY ("instanceStorageInfoId") REFERENCES "instance_storage_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "instance_storage_info_disks_disk_info" ADD CONSTRAINT "FK_f26504b23aa1d0966aedaefa802" FOREIGN KEY ("diskInfoId") REFERENCES "disk_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "fpga_info_fpgas_fpga_device_info" ADD CONSTRAINT "FK_efc682159731f5f8bd2b776ab63" FOREIGN KEY ("fpgaInfoId") REFERENCES "fpga_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "fpga_info_fpgas_fpga_device_info" ADD CONSTRAINT "FK_f1a740c375af691f8fd47908cf1" FOREIGN KEY ("fpgaDeviceInfoId") REFERENCES "fpga_device_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "gpu_info_gpus_gpu_device_info" ADD CONSTRAINT "FK_71b952e068cb2458c680b0ea73a" FOREIGN KEY ("gpuInfoId") REFERENCES "gpu_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "gpu_info_gpus_gpu_device_info" ADD CONSTRAINT "FK_7b8582e2b009b8c08e972e95255" FOREIGN KEY ("gpuDeviceInfoId") REFERENCES "gpu_device_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inference_accelerator_info_accelerators_inference_device_info" ADD CONSTRAINT "FK_a01d9a1f69047f90898bbc75487" FOREIGN KEY ("inferenceAcceleratorInfoId") REFERENCES "inference_accelerator_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inference_accelerator_info_accelerators_inference_device_info" ADD CONSTRAINT "FK_b822f14e8c5d226905e0a1373ec" FOREIGN KEY ("inferenceDeviceInfoId") REFERENCES "inference_device_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "network_info_network_cards_network_card_info" ADD CONSTRAINT "FK_38e3395028d80a8e5a422287dbe" FOREIGN KEY ("networkInfoId") REFERENCES "network_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "network_info_network_cards_network_card_info" ADD CONSTRAINT "FK_9c33046e851961c6f9a131aeb63" FOREIGN KEY ("networkCardInfoId") REFERENCES "network_card_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pla_gro_inf_sup_str_pla_gro_str" ADD CONSTRAINT "FK_df2384ed345ea02b46055287780" FOREIGN KEY ("placementGroupInfoId") REFERENCES "placement_group_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pla_gro_inf_sup_str_pla_gro_str" ADD CONSTRAINT "FK_a9706401551c7ca9fa91d3f47b0" FOREIGN KEY ("placementGroupStrategyId") REFERENCES "placement_group_strategy"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "processor_info_supported_architectures_cpu_architecture" ADD CONSTRAINT "FK_61c1342b3f5ea1eed2a925918ba" FOREIGN KEY ("processorInfoId") REFERENCES "processor_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "processor_info_supported_architectures_cpu_architecture" ADD CONSTRAINT "FK_528f6ad79fa40bed258063306f1" FOREIGN KEY ("cpuArchitectureId") REFERENCES "cpu_architecture"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vcpu_info_valid_cores_valid_core" ADD CONSTRAINT "FK_7627cd35b944da31aa7b70f6473" FOREIGN KEY ("vcpuInfoId") REFERENCES "vcpu_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vcpu_info_valid_cores_valid_core" ADD CONSTRAINT "FK_6bfcecb8b3e69646c70f259cc71" FOREIGN KEY ("validCoreId") REFERENCES "valid_core"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vcpu_info_valid_threads_per_core_valid_threads_per_core" ADD CONSTRAINT "FK_19bde7851ddb55c88d9f83e6b5e" FOREIGN KEY ("vcpuInfoId") REFERENCES "vcpu_info"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vcpu_info_valid_threads_per_core_valid_threads_per_core" ADD CONSTRAINT "FK_ac3a3f74934b0e90a077d2ab5d3" FOREIGN KEY ("validThreadsPerCoreId") REFERENCES "valid_threads_per_core"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_usage_classes_usage_class" ADD CONSTRAINT "FK_ee864286f0efb1f01030c9dc757" FOREIGN KEY ("instanceTypeId") REFERENCES "instance_type"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_usage_classes_usage_class" ADD CONSTRAINT "FK_1dad445b95c880dc668fd01ceb3" FOREIGN KEY ("usageClassId") REFERENCES "usage_class"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_root_device_types_device_type" ADD CONSTRAINT "FK_912b11c90cb1561261c71cd5dc5" FOREIGN KEY ("instanceTypeId") REFERENCES "instance_type"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_root_device_types_device_type" ADD CONSTRAINT "FK_bd4dfa196aae7012c6987887899" FOREIGN KEY ("deviceTypeId") REFERENCES "device_type"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ins_typ_sup_vir_typ_vir_typ" ADD CONSTRAINT "FK_3882f8bb56e24d9ed43d1c4c249" FOREIGN KEY ("instanceTypeId") REFERENCES "instance_type"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ins_typ_sup_vir_typ_vir_typ" ADD CONSTRAINT "FK_f7db3c32e781541f328f0502fa6" FOREIGN KEY ("virtualizationTypeId") REFERENCES "virtualization_type"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_boot_modes_boot_mode" ADD CONSTRAINT "FK_63d531a5057bf5bf18cac8a2f28" FOREIGN KEY ("instanceTypeId") REFERENCES "instance_type"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_boot_modes_boot_mode" ADD CONSTRAINT "FK_d5e1e0258e6532899c373cf7276" FOREIGN KEY ("bootModeId") REFERENCES "boot_mode"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "instance_type_supported_boot_modes_boot_mode" DROP CONSTRAINT "FK_d5e1e0258e6532899c373cf7276"`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_boot_modes_boot_mode" DROP CONSTRAINT "FK_63d531a5057bf5bf18cac8a2f28"`);
        await queryRunner.query(`ALTER TABLE "ins_typ_sup_vir_typ_vir_typ" DROP CONSTRAINT "FK_f7db3c32e781541f328f0502fa6"`);
        await queryRunner.query(`ALTER TABLE "ins_typ_sup_vir_typ_vir_typ" DROP CONSTRAINT "FK_3882f8bb56e24d9ed43d1c4c249"`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_root_device_types_device_type" DROP CONSTRAINT "FK_bd4dfa196aae7012c6987887899"`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_root_device_types_device_type" DROP CONSTRAINT "FK_912b11c90cb1561261c71cd5dc5"`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_usage_classes_usage_class" DROP CONSTRAINT "FK_1dad445b95c880dc668fd01ceb3"`);
        await queryRunner.query(`ALTER TABLE "instance_type_supported_usage_classes_usage_class" DROP CONSTRAINT "FK_ee864286f0efb1f01030c9dc757"`);
        await queryRunner.query(`ALTER TABLE "vcpu_info_valid_threads_per_core_valid_threads_per_core" DROP CONSTRAINT "FK_ac3a3f74934b0e90a077d2ab5d3"`);
        await queryRunner.query(`ALTER TABLE "vcpu_info_valid_threads_per_core_valid_threads_per_core" DROP CONSTRAINT "FK_19bde7851ddb55c88d9f83e6b5e"`);
        await queryRunner.query(`ALTER TABLE "vcpu_info_valid_cores_valid_core" DROP CONSTRAINT "FK_6bfcecb8b3e69646c70f259cc71"`);
        await queryRunner.query(`ALTER TABLE "vcpu_info_valid_cores_valid_core" DROP CONSTRAINT "FK_7627cd35b944da31aa7b70f6473"`);
        await queryRunner.query(`ALTER TABLE "processor_info_supported_architectures_cpu_architecture" DROP CONSTRAINT "FK_528f6ad79fa40bed258063306f1"`);
        await queryRunner.query(`ALTER TABLE "processor_info_supported_architectures_cpu_architecture" DROP CONSTRAINT "FK_61c1342b3f5ea1eed2a925918ba"`);
        await queryRunner.query(`ALTER TABLE "pla_gro_inf_sup_str_pla_gro_str" DROP CONSTRAINT "FK_a9706401551c7ca9fa91d3f47b0"`);
        await queryRunner.query(`ALTER TABLE "pla_gro_inf_sup_str_pla_gro_str" DROP CONSTRAINT "FK_df2384ed345ea02b46055287780"`);
        await queryRunner.query(`ALTER TABLE "network_info_network_cards_network_card_info" DROP CONSTRAINT "FK_9c33046e851961c6f9a131aeb63"`);
        await queryRunner.query(`ALTER TABLE "network_info_network_cards_network_card_info" DROP CONSTRAINT "FK_38e3395028d80a8e5a422287dbe"`);
        await queryRunner.query(`ALTER TABLE "inference_accelerator_info_accelerators_inference_device_info" DROP CONSTRAINT "FK_b822f14e8c5d226905e0a1373ec"`);
        await queryRunner.query(`ALTER TABLE "inference_accelerator_info_accelerators_inference_device_info" DROP CONSTRAINT "FK_a01d9a1f69047f90898bbc75487"`);
        await queryRunner.query(`ALTER TABLE "gpu_info_gpus_gpu_device_info" DROP CONSTRAINT "FK_7b8582e2b009b8c08e972e95255"`);
        await queryRunner.query(`ALTER TABLE "gpu_info_gpus_gpu_device_info" DROP CONSTRAINT "FK_71b952e068cb2458c680b0ea73a"`);
        await queryRunner.query(`ALTER TABLE "fpga_info_fpgas_fpga_device_info" DROP CONSTRAINT "FK_f1a740c375af691f8fd47908cf1"`);
        await queryRunner.query(`ALTER TABLE "fpga_info_fpgas_fpga_device_info" DROP CONSTRAINT "FK_efc682159731f5f8bd2b776ab63"`);
        await queryRunner.query(`ALTER TABLE "instance_storage_info_disks_disk_info" DROP CONSTRAINT "FK_f26504b23aa1d0966aedaefa802"`);
        await queryRunner.query(`ALTER TABLE "instance_storage_info_disks_disk_info" DROP CONSTRAINT "FK_2b12a15c05cc37e279554f5ce7c"`);
        await queryRunner.query(`ALTER TABLE "instance_type" DROP CONSTRAINT "FK_b906f76dd0f0a7a4613bdf4f043"`);
        await queryRunner.query(`ALTER TABLE "instance_type" DROP CONSTRAINT "FK_acadb5566239d7fdbeeb0919729"`);
        await queryRunner.query(`ALTER TABLE "instance_type" DROP CONSTRAINT "FK_e9fd23c6b05997baa8f803f1c17"`);
        await queryRunner.query(`ALTER TABLE "instance_type" DROP CONSTRAINT "FK_7348bb6aba22093bf045157cb55"`);
        await queryRunner.query(`ALTER TABLE "instance_type" DROP CONSTRAINT "FK_8a48290f7e48a213fe6b0931db6"`);
        await queryRunner.query(`ALTER TABLE "instance_type" DROP CONSTRAINT "FK_c74fd39985596ee10d03b405759"`);
        await queryRunner.query(`ALTER TABLE "instance_type" DROP CONSTRAINT "FK_1867d2499134bd841f6dd932161"`);
        await queryRunner.query(`ALTER TABLE "instance_type" DROP CONSTRAINT "FK_a82e73fc00bf3488ee9d93055a7"`);
        await queryRunner.query(`ALTER TABLE "instance_type" DROP CONSTRAINT "FK_837d9c5af92d3108647ba0f6190"`);
        await queryRunner.query(`ALTER TABLE "network_info" DROP CONSTRAINT "FK_5abc0ca3d03456246a6d1eacc84"`);
        await queryRunner.query(`ALTER TABLE "gpu_device_info" DROP CONSTRAINT "FK_175d0ad17acc9c353077ba5d4e3"`);
        await queryRunner.query(`ALTER TABLE "fpga_device_info" DROP CONSTRAINT "FK_c83fc8695a42bc116e46db17bf6"`);
        await queryRunner.query(`ALTER TABLE "ebs_info" DROP CONSTRAINT "FK_c0d05e1ff186d9c4d26ed747d08"`);
        await queryRunner.query(`DROP INDEX "IDX_d5e1e0258e6532899c373cf727"`);
        await queryRunner.query(`DROP INDEX "IDX_63d531a5057bf5bf18cac8a2f2"`);
        await queryRunner.query(`DROP TABLE "instance_type_supported_boot_modes_boot_mode"`);
        await queryRunner.query(`DROP INDEX "IDX_f7db3c32e781541f328f0502fa"`);
        await queryRunner.query(`DROP INDEX "IDX_3882f8bb56e24d9ed43d1c4c24"`);
        await queryRunner.query(`DROP TABLE "ins_typ_sup_vir_typ_vir_typ"`);
        await queryRunner.query(`DROP INDEX "IDX_bd4dfa196aae7012c698788789"`);
        await queryRunner.query(`DROP INDEX "IDX_912b11c90cb1561261c71cd5dc"`);
        await queryRunner.query(`DROP TABLE "instance_type_supported_root_device_types_device_type"`);
        await queryRunner.query(`DROP INDEX "IDX_1dad445b95c880dc668fd01ceb"`);
        await queryRunner.query(`DROP INDEX "IDX_ee864286f0efb1f01030c9dc75"`);
        await queryRunner.query(`DROP TABLE "instance_type_supported_usage_classes_usage_class"`);
        await queryRunner.query(`DROP INDEX "IDX_ac3a3f74934b0e90a077d2ab5d"`);
        await queryRunner.query(`DROP INDEX "IDX_19bde7851ddb55c88d9f83e6b5"`);
        await queryRunner.query(`DROP TABLE "vcpu_info_valid_threads_per_core_valid_threads_per_core"`);
        await queryRunner.query(`DROP INDEX "IDX_6bfcecb8b3e69646c70f259cc7"`);
        await queryRunner.query(`DROP INDEX "IDX_7627cd35b944da31aa7b70f647"`);
        await queryRunner.query(`DROP TABLE "vcpu_info_valid_cores_valid_core"`);
        await queryRunner.query(`DROP INDEX "IDX_528f6ad79fa40bed258063306f"`);
        await queryRunner.query(`DROP INDEX "IDX_61c1342b3f5ea1eed2a925918b"`);
        await queryRunner.query(`DROP TABLE "processor_info_supported_architectures_cpu_architecture"`);
        await queryRunner.query(`DROP INDEX "IDX_a9706401551c7ca9fa91d3f47b"`);
        await queryRunner.query(`DROP INDEX "IDX_df2384ed345ea02b4605528778"`);
        await queryRunner.query(`DROP TABLE "pla_gro_inf_sup_str_pla_gro_str"`);
        await queryRunner.query(`DROP INDEX "IDX_9c33046e851961c6f9a131aeb6"`);
        await queryRunner.query(`DROP INDEX "IDX_38e3395028d80a8e5a422287db"`);
        await queryRunner.query(`DROP TABLE "network_info_network_cards_network_card_info"`);
        await queryRunner.query(`DROP INDEX "IDX_b822f14e8c5d226905e0a1373e"`);
        await queryRunner.query(`DROP INDEX "IDX_a01d9a1f69047f90898bbc7548"`);
        await queryRunner.query(`DROP TABLE "inference_accelerator_info_accelerators_inference_device_info"`);
        await queryRunner.query(`DROP INDEX "IDX_7b8582e2b009b8c08e972e9525"`);
        await queryRunner.query(`DROP INDEX "IDX_71b952e068cb2458c680b0ea73"`);
        await queryRunner.query(`DROP TABLE "gpu_info_gpus_gpu_device_info"`);
        await queryRunner.query(`DROP INDEX "IDX_f1a740c375af691f8fd47908cf"`);
        await queryRunner.query(`DROP INDEX "IDX_efc682159731f5f8bd2b776ab6"`);
        await queryRunner.query(`DROP TABLE "fpga_info_fpgas_fpga_device_info"`);
        await queryRunner.query(`DROP INDEX "IDX_f26504b23aa1d0966aedaefa80"`);
        await queryRunner.query(`DROP INDEX "IDX_2b12a15c05cc37e279554f5ce7"`);
        await queryRunner.query(`DROP TABLE "instance_storage_info_disks_disk_info"`);
        await queryRunner.query(`DROP TABLE "instance_type"`);
        await queryRunner.query(`DROP TYPE "instance_type_hypervisor_enum"`);
        await queryRunner.query(`DROP TYPE "instance_type_instancetype_enum"`);
        await queryRunner.query(`DROP TABLE "virtualization_type"`);
        await queryRunner.query(`DROP TABLE "vcpu_info"`);
        await queryRunner.query(`DROP TABLE "valid_threads_per_core"`);
        await queryRunner.query(`DROP TABLE "valid_core"`);
        await queryRunner.query(`DROP TABLE "usage_class"`);
        await queryRunner.query(`DROP TABLE "processor_info"`);
        await queryRunner.query(`DROP TABLE "placement_group_info"`);
        await queryRunner.query(`DROP TABLE "placement_group_strategy"`);
        await queryRunner.query(`DROP TABLE "network_info"`);
        await queryRunner.query(`DROP TYPE "network_info_enasupport_enum"`);
        await queryRunner.query(`DROP TABLE "network_card_info"`);
        await queryRunner.query(`DROP TABLE "inference_accelerator_info"`);
        await queryRunner.query(`DROP TABLE "inference_device_info"`);
        await queryRunner.query(`DROP TABLE "gpu_info"`);
        await queryRunner.query(`DROP TABLE "gpu_device_info"`);
        await queryRunner.query(`DROP TABLE "gpu_device_memory_info"`);
        await queryRunner.query(`DROP TABLE "fpga_info"`);
        await queryRunner.query(`DROP TABLE "fpga_device_info"`);
        await queryRunner.query(`DROP TABLE "fpga_device_memory_info"`);
        await queryRunner.query(`DROP TABLE "efa_info"`);
        await queryRunner.query(`DROP TABLE "ebs_info"`);
        await queryRunner.query(`DROP TYPE "ebs_info_nvmesupport_enum"`);
        await queryRunner.query(`DROP TYPE "ebs_info_encryptionsupport_enum"`);
        await queryRunner.query(`DROP TYPE "ebs_info_ebsoptimizedsupport_enum"`);
        await queryRunner.query(`DROP TABLE "instance_storage_info"`);
        await queryRunner.query(`DROP TYPE "instance_storage_info_nvmesupport_enum"`);
        await queryRunner.query(`DROP TABLE "ebs_optimized_info"`);
        await queryRunner.query(`DROP TABLE "disk_info"`);
        await queryRunner.query(`DROP TYPE "disk_info_type_enum"`);
        await queryRunner.query(`DROP TABLE "device_type"`);
        await queryRunner.query(`DROP TABLE "cpu_architecture"`);
        await queryRunner.query(`DROP TABLE "boot_mode"`);
    }

}
