import {MigrationInterface, QueryRunner} from "typeorm";

export class rds1634207752956 implements MigrationInterface {
    name = 'rds1634207752956'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "disk_info" RENAME COLUMN "type" TO "disk_type"`);
        await queryRunner.query(`ALTER TYPE "public"."disk_info_type_enum" RENAME TO "disk_info_disk_type_enum"`);
        await queryRunner.query(`CREATE TABLE "activity_stream_mode" ("id" SERIAL NOT NULL, "mode" character varying NOT NULL, CONSTRAINT "UQ_2495c911d618977ab170eaf9179" UNIQUE ("mode"), CONSTRAINT "PK_ecc0a022d867dfdfdb1a8b6a4aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "character_set" ("id" SERIAL NOT NULL, "character_set_name" character varying NOT NULL, "character_set_description" character varying, CONSTRAINT "UQ_bd3acc10c6e3e46d395dbd62f38" UNIQUE ("character_set_name"), CONSTRAINT "PK_c8e16ff898530271ff50d765911" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cloudwatch_logs_export" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_9fb0d25617e24914a2dbd0cc3d0" UNIQUE ("name"), CONSTRAINT "PK_62bf7e06f5a3108f1a5718a04d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "db_instance_class" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_671cddb2858888a104b6ed827c8" UNIQUE ("name"), CONSTRAINT "PK_6f121e752f8b41bef4c04d20d83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "db_parameter_group_status" ("id" SERIAL NOT NULL, "db_parameter_group_name" character varying, "parameter_apply_status" character varying, CONSTRAINT "PK_a259f265745cb6dd5305e4e4e10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exportable_log_type" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_90b5b4a640e4111b86f0a514beb" UNIQUE ("name"), CONSTRAINT "PK_b7ac936668c10ffe2d81ecc490c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "feature_name" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_d9dfdaf97be65a71234a1e151aa" UNIQUE ("name"), CONSTRAINT "PK_5370835a735374d9d2d3e442281" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supported_engine_mode" ("id" SERIAL NOT NULL, "mode" character varying NOT NULL, CONSTRAINT "UQ_195226533f376ca48d7f23d0e26" UNIQUE ("mode"), CONSTRAINT "PK_5f6ac090ecf0f92d5a6dcc73e0f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "timezone" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_416ff1a8aedc587a4b907606f1c" UNIQUE ("name"), CONSTRAINT "PK_2706edc3223dd1d219f9f6a11b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "engine_version" ("id" SERIAL NOT NULL, "engine" character varying NOT NULL, "engine_version" character varying NOT NULL, "db_parameter_group_family" character varying NOT NULL, "db_engine_description" character varying NOT NULL, "db_engine_version_description" character varying NOT NULL, "supports_log_exports_to_cloudwatch_logs" boolean NOT NULL, "supports_read_replica" boolean NOT NULL, "status" character varying NOT NULL, "supports_parallel_query" boolean NOT NULL, "supports_global_databases" boolean NOT NULL, "character_set_id" integer, CONSTRAINT "UQ_ed96cab69ec37aed3821a4425c7" UNIQUE ("engine_version"), CONSTRAINT "PK_78ce275dc827b0733a45c79d6a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "upgrade_target" ("id" SERIAL NOT NULL, "description" character varying, "auto_upgrade" boolean, "is_major_version_upgrade" boolean, "supports_parallel_query" boolean, "supports_global_databases" boolean, "engine_version_id" integer, CONSTRAINT "PK_f9be5fc5d0f96f9c2cfebeb3c40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "processor_feature" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "value" character varying, CONSTRAINT "PK_8b6199d7f33829240aee38da83d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orderable_db_instance_option" ("id" SERIAL NOT NULL, "license_model" character varying, "multi_az_capable" boolean, "read_replica_capable" boolean, "vpc" boolean, "supports_storage_encryption" boolean, "storage_type" character varying, "supports_iops" boolean, "supports_enhanced_monitoring" boolean, "supports_iam_database_authentication" boolean, "supports_performance_insights" boolean, "min_storage_size" numeric, "max_storage_size" numeric, "min_iops_per_db_instance" numeric, "max_iops_per_db_instance" numeric, "min_iops_per_gib" numeric, "max_iops_per_gib" numeric, "supports_storage_autoscaling" boolean, "supports_kerberos_authentication" boolean, "outpost_capable" boolean, "supports_global_databases" boolean, "engine_version_id" integer, "db_instance_class_id" integer, CONSTRAINT "PK_b3b32923ec60debecf4a5ddeaec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "domain_membership" ("id" SERIAL NOT NULL, "domain" character varying, "status" character varying, "fqdn" character varying, "iam_role_name" character varying, CONSTRAINT "PK_d015c1d1a3584be1afdea928ece" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "option_group_membership" ("id" SERIAL NOT NULL, "option_group_name" character varying, "status" character varying, CONSTRAINT "PK_edc58af19ca145174e323888d2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "endpoint" ("id" SERIAL NOT NULL, "address" character varying, "port" integer, "hosted_zone_id" character varying, CONSTRAINT "PK_7785c5c2cf24e6ab3abb7a2e89f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rds_storage_type_enum" AS ENUM('standard', 'gp2', 'io1')`);
        await queryRunner.query(`CREATE TYPE "public"."rds_activity_stream_status_enum" AS ENUM('started', 'starting', 'stopped', 'stopping')`);
        await queryRunner.query(`CREATE TYPE "public"."rds_replica_mode_enum" AS ENUM('mounted', 'open-read-only')`);
        await queryRunner.query(`CREATE TABLE "rds" ("id" SERIAL NOT NULL, "dbi_resource_id" character varying, "db_instance_identifier" character varying NOT NULL, "allocated_storage" integer NOT NULL, "auto_minor_version_upgrade" boolean, "backup_retention_period" integer DEFAULT '1', "character_set_name" character varying, "copy_tags_to_snapshot" boolean DEFAULT false, "db_cluster_identifier" character varying, "db_name" character varying, "deletion_protection" boolean DEFAULT false, "enable_customer_owned_ip" boolean, "enable_iam_database_authentication" boolean DEFAULT false, "enable_performance_insights" boolean, "iops" integer, "kms_key_id" character varying, "license_model" character varying, "master_user_password" character varying, "master_username" character varying, "max_allocated_storage" integer, "monitoring_interval" integer NOT NULL DEFAULT '0', "monitoring_role_arn" character varying, "multi_az" boolean, "nchar_character_set_name" character varying, "performance_insights_kms_key_id" character varying, "performance_insights_retention_period" integer, "port" integer, "preferred_backup_window" character varying, "preferred_maintenance_window" character varying, "promotion_tier" integer DEFAULT '1', "publicly_accessible" boolean, "storage_encrypted" boolean, "storage_type" "public"."rds_storage_type_enum", "tde_credential_arn" character varying, "tde_credential_password" character varying, "timezone" character varying, "db_instance_status" character varying, "automatic_restart_time" TIMESTAMP WITH TIME ZONE, "instance_create_time" TIMESTAMP WITH TIME ZONE, "db_subnet_group" character varying, "latest_restorable_time" TIMESTAMP WITH TIME ZONE, "ca_certificate_identifier" character varying, "db_instance_arn" character varying, "associated_roles" character varying, "aws_backup_recovery_point_arn" character varying, "activity_stream_status" "public"."rds_activity_stream_status_enum", "activity_stream_kms_key_id" character varying, "activity_stream_kinesis_stream_name" character varying, "activity_stream_engine_native_audit_fields_included" boolean, "read_replica_source_db_instance_identifier" character varying, "read_replica_db_instance_identifiers" character varying, "read_replica_db_cluster_identifiers" character varying, "replica_mode" "public"."rds_replica_mode_enum", "status_infos" character varying, "db_instance_automated_backups_replications" character varying, "availability_zone_id" integer, "db_instance_class_id" integer, "engine_version_id" integer, "endpoint_id" integer, "secondary_availability_zone_id" integer, "listener_endpoint_id" integer, "activity_stream_mode_id" integer, CONSTRAINT "UQ_7fb01956cebcabd694baf5f1f6b" UNIQUE ("db_instance_identifier"), CONSTRAINT "PK_67d6c2133366c8eda49b40de7b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "engine_version_valid_upgrade_targets_upgrade_target" ("engine_version_id" integer NOT NULL, "upgrade_target_id" integer NOT NULL, CONSTRAINT "PK_d023ecc41c465d76b0af52f16ca" PRIMARY KEY ("engine_version_id", "upgrade_target_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0b9d53fadcfc2b156c0578e26a" ON "engine_version_valid_upgrade_targets_upgrade_target" ("engine_version_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f6eada6a897f57e03afdca8b4" ON "engine_version_valid_upgrade_targets_upgrade_target" ("upgrade_target_id") `);
        await queryRunner.query(`CREATE TABLE "engine_version_exportable_log_types_exportable_log_type" ("engine_version_id" integer NOT NULL, "exportable_log_type_id" integer NOT NULL, CONSTRAINT "PK_115e1f1629c8f9c750065fb7690" PRIMARY KEY ("engine_version_id", "exportable_log_type_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_213878cf8b7fe21a798590901e" ON "engine_version_exportable_log_types_exportable_log_type" ("engine_version_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_20d6999924d3689ce9c6feba0b" ON "engine_version_exportable_log_types_exportable_log_type" ("exportable_log_type_id") `);
        await queryRunner.query(`CREATE TABLE "engine_version_supported_engine_modes_supported_engine_mode" ("engine_version_id" integer NOT NULL, "supported_engine_mode_id" integer NOT NULL, CONSTRAINT "PK_516df2eba438f65ec8309fa994b" PRIMARY KEY ("engine_version_id", "supported_engine_mode_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5219b2e9e7239aedab4c0efd88" ON "engine_version_supported_engine_modes_supported_engine_mode" ("engine_version_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf981feb7226ab1eea1f8137e9" ON "engine_version_supported_engine_modes_supported_engine_mode" ("supported_engine_mode_id") `);
        await queryRunner.query(`CREATE TABLE "engine_version_supported_character_sets_character_set" ("engine_version_id" integer NOT NULL, "character_set_id" integer NOT NULL, CONSTRAINT "PK_752f008f747621e83a72c53d361" PRIMARY KEY ("engine_version_id", "character_set_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c75893914eaa6b126d86ea1107" ON "engine_version_supported_character_sets_character_set" ("engine_version_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_40ee09086af8e73dfb789cf4ae" ON "engine_version_supported_character_sets_character_set" ("character_set_id") `);
        await queryRunner.query(`CREATE TABLE "engine_version_supported_nchar_character_sets_character_set" ("engine_version_id" integer NOT NULL, "character_set_id" integer NOT NULL, CONSTRAINT "PK_05e88ddba1d2942a3975a3e01dc" PRIMARY KEY ("engine_version_id", "character_set_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3fe9d74aca258c5be138cbd318" ON "engine_version_supported_nchar_character_sets_character_set" ("engine_version_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ddb19763885c9409cdd63e1201" ON "engine_version_supported_nchar_character_sets_character_set" ("character_set_id") `);
        await queryRunner.query(`CREATE TABLE "engine_version_supported_feature_names_feature_name" ("engine_version_id" integer NOT NULL, "feature_name_id" integer NOT NULL, CONSTRAINT "PK_f22a8b668488008f63e8307739b" PRIMARY KEY ("engine_version_id", "feature_name_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b21e21f9cc5b3912ceb61ac99" ON "engine_version_supported_feature_names_feature_name" ("engine_version_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6143d3a09a41fa2dd555631ff" ON "engine_version_supported_feature_names_feature_name" ("feature_name_id") `);
        await queryRunner.query(`CREATE TABLE "engine_version_supported_timezones_timezone" ("engine_version_id" integer NOT NULL, "timezone_id" integer NOT NULL, CONSTRAINT "PK_043b9488caca8ab35ae33713bd3" PRIMARY KEY ("engine_version_id", "timezone_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5e596e02a6f9cae013ef16ccb0" ON "engine_version_supported_timezones_timezone" ("engine_version_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bf722a82544147511e5f305d0" ON "engine_version_supported_timezones_timezone" ("timezone_id") `);
        await queryRunner.query(`CREATE TABLE "upgrade_target_supported_engine_modes_supported_engine_mode" ("upgrade_target_id" integer NOT NULL, "supported_engine_mode_id" integer NOT NULL, CONSTRAINT "PK_d84ae331737da89ef03ad5e18a5" PRIMARY KEY ("upgrade_target_id", "supported_engine_mode_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8d9873989625cd727e2849357e" ON "upgrade_target_supported_engine_modes_supported_engine_mode" ("upgrade_target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5eb731c791fd72e2159a82ff94" ON "upgrade_target_supported_engine_modes_supported_engine_mode" ("supported_engine_mode_id") `);
        await queryRunner.query(`CREATE TABLE "ord_db_ins_opt_ava_zon_ava_zon" ("orderable_db_instance_option_id" integer NOT NULL, "availability_zone_id" integer NOT NULL, CONSTRAINT "PK_325b3bc7677d3abeb1cce76e182" PRIMARY KEY ("orderable_db_instance_option_id", "availability_zone_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f51aaa97cb0a59e1894dd10d80" ON "ord_db_ins_opt_ava_zon_ava_zon" ("orderable_db_instance_option_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_06b84b8cd688f4c5fccf4358c2" ON "ord_db_ins_opt_ava_zon_ava_zon" ("availability_zone_id") `);
        await queryRunner.query(`CREATE TABLE "ord_db_ins_opt_ava_pro_fea_pro_fea" ("orderable_db_instance_option_id" integer NOT NULL, "processor_feature_id" integer NOT NULL, CONSTRAINT "PK_67d0ac673dc83d08ce27239cc31" PRIMARY KEY ("orderable_db_instance_option_id", "processor_feature_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_19e4eab2447c349de981bcd3dc" ON "ord_db_ins_opt_ava_pro_fea_pro_fea" ("orderable_db_instance_option_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb0adb88702053dd6f1cc7d968" ON "ord_db_ins_opt_ava_pro_fea_pro_fea" ("processor_feature_id") `);
        await queryRunner.query(`CREATE TABLE "ord_db_ins_opt_sup_eng_mod_sup_eng_mod" ("orderable_db_instance_option_id" integer NOT NULL, "supported_engine_mode_id" integer NOT NULL, CONSTRAINT "PK_6b1ca5424ad370cdf7bae9deb8a" PRIMARY KEY ("orderable_db_instance_option_id", "supported_engine_mode_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_704d81d4ab7a482a7fb3944888" ON "ord_db_ins_opt_sup_eng_mod_sup_eng_mod" ("orderable_db_instance_option_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3998b7d52519d19f2303e0b2ce" ON "ord_db_ins_opt_sup_eng_mod_sup_eng_mod" ("supported_engine_mode_id") `);
        await queryRunner.query(`CREATE TABLE "ord_db_ins_opt_sup_act_str_mod_act_str_mod" ("orderable_db_instance_option_id" integer NOT NULL, "activity_stream_mode_id" integer NOT NULL, CONSTRAINT "PK_586481cf0e2adbe468fb10b2d37" PRIMARY KEY ("orderable_db_instance_option_id", "activity_stream_mode_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c913ba69d17aa321078fda7250" ON "ord_db_ins_opt_sup_act_str_mod_act_str_mod" ("orderable_db_instance_option_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3467c284d2ce88aabf61abd13" ON "ord_db_ins_opt_sup_act_str_mod_act_str_mod" ("activity_stream_mode_id") `);
        await queryRunner.query(`CREATE TABLE "rds_db_parameter_groups_db_parameter_group_status" ("rds_id" integer NOT NULL, "db_parameter_group_status_id" integer NOT NULL, CONSTRAINT "PK_2e2c82c8fb4576e9247a336b753" PRIMARY KEY ("rds_id", "db_parameter_group_status_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_388be0f10930095b8f207ef070" ON "rds_db_parameter_groups_db_parameter_group_status" ("rds_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4aa131803a030d058fe4abb7fe" ON "rds_db_parameter_groups_db_parameter_group_status" ("db_parameter_group_status_id") `);
        await queryRunner.query(`CREATE TABLE "rds_domain_memberships_domain_membership" ("rds_id" integer NOT NULL, "domain_membership_id" integer NOT NULL, CONSTRAINT "PK_200f4a5b906c8a4a6f48b544e5a" PRIMARY KEY ("rds_id", "domain_membership_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5e9a0a3f9d6ef14aaac0cf9663" ON "rds_domain_memberships_domain_membership" ("rds_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1af07c6514ee027a2dc85ac79f" ON "rds_domain_memberships_domain_membership" ("domain_membership_id") `);
        await queryRunner.query(`CREATE TABLE "rds_enabled_cloudwatch_logs_exports_cloudwatch_logs_export" ("rds_id" integer NOT NULL, "cloudwatch_logs_export_id" integer NOT NULL, CONSTRAINT "PK_91c58391cbb032e3940350f286b" PRIMARY KEY ("rds_id", "cloudwatch_logs_export_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8665c22521b74fcc1036760c57" ON "rds_enabled_cloudwatch_logs_exports_cloudwatch_logs_export" ("rds_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_edb9b1dc35e66b8e090cc855e2" ON "rds_enabled_cloudwatch_logs_exports_cloudwatch_logs_export" ("cloudwatch_logs_export_id") `);
        await queryRunner.query(`CREATE TABLE "rds_option_group_memberships_option_group_membership" ("rds_id" integer NOT NULL, "option_group_membership_id" integer NOT NULL, CONSTRAINT "PK_12f3f55ee9bf416b13b474ece50" PRIMARY KEY ("rds_id", "option_group_membership_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_46a3198cc9c5fc5c423422dfb7" ON "rds_option_group_memberships_option_group_membership" ("rds_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_21d2baf09d1f84ca46f77c287a" ON "rds_option_group_memberships_option_group_membership" ("option_group_membership_id") `);
        await queryRunner.query(`CREATE TABLE "rds_processor_features_processor_feature" ("rds_id" integer NOT NULL, "processor_feature_id" integer NOT NULL, CONSTRAINT "PK_466a9fbbfbfe991cb67303b5e8f" PRIMARY KEY ("rds_id", "processor_feature_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_040989e476315840c5bc4f0c6d" ON "rds_processor_features_processor_feature" ("rds_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_568be2825b0cb4b0badc098c3b" ON "rds_processor_features_processor_feature" ("processor_feature_id") `);
        await queryRunner.query(`CREATE TABLE "rds_tags_tag" ("rds_id" integer NOT NULL, "tag_id" integer NOT NULL, CONSTRAINT "PK_064878365c3757e6fb2baee6b02" PRIMARY KEY ("rds_id", "tag_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2df06d9732e153c117aa5e22d6" ON "rds_tags_tag" ("rds_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c8e70858e8f1e5d846414914e" ON "rds_tags_tag" ("tag_id") `);
        await queryRunner.query(`CREATE TABLE "rds_vpc_security_groups_security_group" ("rds_id" integer NOT NULL, "security_group_id" integer NOT NULL, CONSTRAINT "PK_d1ffa733808d137bc741f2fad22" PRIMARY KEY ("rds_id", "security_group_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f8d69062593d90e1d7a575463" ON "rds_vpc_security_groups_security_group" ("rds_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d8771bbe0783f3ff703bdb7e99" ON "rds_vpc_security_groups_security_group" ("security_group_id") `);
        await queryRunner.query(`ALTER TABLE "network_info" DROP COLUMN "ipv4addresses_per_interface"`);
        await queryRunner.query(`ALTER TABLE "network_info" DROP COLUMN "ipv6addresses_per_interface"`);
        await queryRunner.query(`ALTER TABLE "network_info" DROP COLUMN "ipv6supported"`);
        await queryRunner.query(`ALTER TABLE "network_info" ADD "ipv4_addresses_per_interface" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "network_info" ADD "ipv6_addresses_per_interface" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "network_info" ADD "ipv6_supported" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "engine_version" ADD CONSTRAINT "FK_87600ab5ee44e3d1d2c7bb01083" FOREIGN KEY ("character_set_id") REFERENCES "character_set"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upgrade_target" ADD CONSTRAINT "FK_f72e551ae46bb42c1b7d5c0c958" FOREIGN KEY ("engine_version_id") REFERENCES "engine_version"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orderable_db_instance_option" ADD CONSTRAINT "FK_b2609a55c9361c6c05549bb3e22" FOREIGN KEY ("engine_version_id") REFERENCES "engine_version"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orderable_db_instance_option" ADD CONSTRAINT "FK_46e53cc6bc7fcf5aec05a444ac7" FOREIGN KEY ("db_instance_class_id") REFERENCES "db_instance_class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rds" ADD CONSTRAINT "FK_88d7baba1011b1d780d4087e401" FOREIGN KEY ("availability_zone_id") REFERENCES "availability_zone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rds" ADD CONSTRAINT "FK_f78aee03934884ec12ed206c6ee" FOREIGN KEY ("db_instance_class_id") REFERENCES "db_instance_class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rds" ADD CONSTRAINT "FK_f0c9a8ba920bd21d2f2833e1d92" FOREIGN KEY ("engine_version_id") REFERENCES "engine_version"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rds" ADD CONSTRAINT "FK_505a7144df2d71295aac1bf0da0" FOREIGN KEY ("endpoint_id") REFERENCES "endpoint"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rds" ADD CONSTRAINT "FK_8e3b0a8a106963b1b17af2bd674" FOREIGN KEY ("secondary_availability_zone_id") REFERENCES "availability_zone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rds" ADD CONSTRAINT "FK_7a5a4239f36cb66f08e56ffcf1c" FOREIGN KEY ("listener_endpoint_id") REFERENCES "endpoint"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rds" ADD CONSTRAINT "FK_dab66e009d8ba438e795c9f2105" FOREIGN KEY ("activity_stream_mode_id") REFERENCES "activity_stream_mode"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engine_version_valid_upgrade_targets_upgrade_target" ADD CONSTRAINT "FK_0b9d53fadcfc2b156c0578e26ab" FOREIGN KEY ("engine_version_id") REFERENCES "engine_version"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_valid_upgrade_targets_upgrade_target" ADD CONSTRAINT "FK_3f6eada6a897f57e03afdca8b49" FOREIGN KEY ("upgrade_target_id") REFERENCES "upgrade_target"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_exportable_log_types_exportable_log_type" ADD CONSTRAINT "FK_213878cf8b7fe21a798590901e6" FOREIGN KEY ("engine_version_id") REFERENCES "engine_version"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_exportable_log_types_exportable_log_type" ADD CONSTRAINT "FK_20d6999924d3689ce9c6feba0bb" FOREIGN KEY ("exportable_log_type_id") REFERENCES "exportable_log_type"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_engine_modes_supported_engine_mode" ADD CONSTRAINT "FK_5219b2e9e7239aedab4c0efd880" FOREIGN KEY ("engine_version_id") REFERENCES "engine_version"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_engine_modes_supported_engine_mode" ADD CONSTRAINT "FK_bf981feb7226ab1eea1f8137e93" FOREIGN KEY ("supported_engine_mode_id") REFERENCES "supported_engine_mode"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_character_sets_character_set" ADD CONSTRAINT "FK_c75893914eaa6b126d86ea1107c" FOREIGN KEY ("engine_version_id") REFERENCES "engine_version"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_character_sets_character_set" ADD CONSTRAINT "FK_40ee09086af8e73dfb789cf4aea" FOREIGN KEY ("character_set_id") REFERENCES "character_set"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_nchar_character_sets_character_set" ADD CONSTRAINT "FK_3fe9d74aca258c5be138cbd318c" FOREIGN KEY ("engine_version_id") REFERENCES "engine_version"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_nchar_character_sets_character_set" ADD CONSTRAINT "FK_ddb19763885c9409cdd63e12013" FOREIGN KEY ("character_set_id") REFERENCES "character_set"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_feature_names_feature_name" ADD CONSTRAINT "FK_9b21e21f9cc5b3912ceb61ac999" FOREIGN KEY ("engine_version_id") REFERENCES "engine_version"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_feature_names_feature_name" ADD CONSTRAINT "FK_d6143d3a09a41fa2dd555631ffc" FOREIGN KEY ("feature_name_id") REFERENCES "feature_name"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_timezones_timezone" ADD CONSTRAINT "FK_5e596e02a6f9cae013ef16ccb03" FOREIGN KEY ("engine_version_id") REFERENCES "engine_version"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_timezones_timezone" ADD CONSTRAINT "FK_8bf722a82544147511e5f305d0f" FOREIGN KEY ("timezone_id") REFERENCES "timezone"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "upgrade_target_supported_engine_modes_supported_engine_mode" ADD CONSTRAINT "FK_8d9873989625cd727e2849357e6" FOREIGN KEY ("upgrade_target_id") REFERENCES "upgrade_target"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "upgrade_target_supported_engine_modes_supported_engine_mode" ADD CONSTRAINT "FK_5eb731c791fd72e2159a82ff948" FOREIGN KEY ("supported_engine_mode_id") REFERENCES "supported_engine_mode"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_ava_zon_ava_zon" ADD CONSTRAINT "FK_f51aaa97cb0a59e1894dd10d804" FOREIGN KEY ("orderable_db_instance_option_id") REFERENCES "orderable_db_instance_option"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_ava_zon_ava_zon" ADD CONSTRAINT "FK_06b84b8cd688f4c5fccf4358c21" FOREIGN KEY ("availability_zone_id") REFERENCES "availability_zone"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_ava_pro_fea_pro_fea" ADD CONSTRAINT "FK_19e4eab2447c349de981bcd3dc9" FOREIGN KEY ("orderable_db_instance_option_id") REFERENCES "orderable_db_instance_option"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_ava_pro_fea_pro_fea" ADD CONSTRAINT "FK_bb0adb88702053dd6f1cc7d9689" FOREIGN KEY ("processor_feature_id") REFERENCES "processor_feature"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_sup_eng_mod_sup_eng_mod" ADD CONSTRAINT "FK_704d81d4ab7a482a7fb39448887" FOREIGN KEY ("orderable_db_instance_option_id") REFERENCES "orderable_db_instance_option"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_sup_eng_mod_sup_eng_mod" ADD CONSTRAINT "FK_3998b7d52519d19f2303e0b2ce8" FOREIGN KEY ("supported_engine_mode_id") REFERENCES "supported_engine_mode"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_sup_act_str_mod_act_str_mod" ADD CONSTRAINT "FK_c913ba69d17aa321078fda72506" FOREIGN KEY ("orderable_db_instance_option_id") REFERENCES "orderable_db_instance_option"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_sup_act_str_mod_act_str_mod" ADD CONSTRAINT "FK_f3467c284d2ce88aabf61abd135" FOREIGN KEY ("activity_stream_mode_id") REFERENCES "activity_stream_mode"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_db_parameter_groups_db_parameter_group_status" ADD CONSTRAINT "FK_388be0f10930095b8f207ef070f" FOREIGN KEY ("rds_id") REFERENCES "rds"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_db_parameter_groups_db_parameter_group_status" ADD CONSTRAINT "FK_4aa131803a030d058fe4abb7fed" FOREIGN KEY ("db_parameter_group_status_id") REFERENCES "db_parameter_group_status"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_domain_memberships_domain_membership" ADD CONSTRAINT "FK_5e9a0a3f9d6ef14aaac0cf9663e" FOREIGN KEY ("rds_id") REFERENCES "rds"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_domain_memberships_domain_membership" ADD CONSTRAINT "FK_1af07c6514ee027a2dc85ac79f8" FOREIGN KEY ("domain_membership_id") REFERENCES "domain_membership"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_enabled_cloudwatch_logs_exports_cloudwatch_logs_export" ADD CONSTRAINT "FK_8665c22521b74fcc1036760c572" FOREIGN KEY ("rds_id") REFERENCES "rds"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_enabled_cloudwatch_logs_exports_cloudwatch_logs_export" ADD CONSTRAINT "FK_edb9b1dc35e66b8e090cc855e2f" FOREIGN KEY ("cloudwatch_logs_export_id") REFERENCES "cloudwatch_logs_export"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_option_group_memberships_option_group_membership" ADD CONSTRAINT "FK_46a3198cc9c5fc5c423422dfb73" FOREIGN KEY ("rds_id") REFERENCES "rds"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_option_group_memberships_option_group_membership" ADD CONSTRAINT "FK_21d2baf09d1f84ca46f77c287a1" FOREIGN KEY ("option_group_membership_id") REFERENCES "option_group_membership"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_processor_features_processor_feature" ADD CONSTRAINT "FK_040989e476315840c5bc4f0c6d4" FOREIGN KEY ("rds_id") REFERENCES "rds"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_processor_features_processor_feature" ADD CONSTRAINT "FK_568be2825b0cb4b0badc098c3bc" FOREIGN KEY ("processor_feature_id") REFERENCES "processor_feature"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_tags_tag" ADD CONSTRAINT "FK_2df06d9732e153c117aa5e22d63" FOREIGN KEY ("rds_id") REFERENCES "rds"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_tags_tag" ADD CONSTRAINT "FK_8c8e70858e8f1e5d846414914ef" FOREIGN KEY ("tag_id") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_vpc_security_groups_security_group" ADD CONSTRAINT "FK_3f8d69062593d90e1d7a575463f" FOREIGN KEY ("rds_id") REFERENCES "rds"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rds_vpc_security_groups_security_group" ADD CONSTRAINT "FK_d8771bbe0783f3ff703bdb7e993" FOREIGN KEY ("security_group_id") REFERENCES "security_group"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rds_vpc_security_groups_security_group" DROP CONSTRAINT "FK_d8771bbe0783f3ff703bdb7e993"`);
        await queryRunner.query(`ALTER TABLE "rds_vpc_security_groups_security_group" DROP CONSTRAINT "FK_3f8d69062593d90e1d7a575463f"`);
        await queryRunner.query(`ALTER TABLE "rds_tags_tag" DROP CONSTRAINT "FK_8c8e70858e8f1e5d846414914ef"`);
        await queryRunner.query(`ALTER TABLE "rds_tags_tag" DROP CONSTRAINT "FK_2df06d9732e153c117aa5e22d63"`);
        await queryRunner.query(`ALTER TABLE "rds_processor_features_processor_feature" DROP CONSTRAINT "FK_568be2825b0cb4b0badc098c3bc"`);
        await queryRunner.query(`ALTER TABLE "rds_processor_features_processor_feature" DROP CONSTRAINT "FK_040989e476315840c5bc4f0c6d4"`);
        await queryRunner.query(`ALTER TABLE "rds_option_group_memberships_option_group_membership" DROP CONSTRAINT "FK_21d2baf09d1f84ca46f77c287a1"`);
        await queryRunner.query(`ALTER TABLE "rds_option_group_memberships_option_group_membership" DROP CONSTRAINT "FK_46a3198cc9c5fc5c423422dfb73"`);
        await queryRunner.query(`ALTER TABLE "rds_enabled_cloudwatch_logs_exports_cloudwatch_logs_export" DROP CONSTRAINT "FK_edb9b1dc35e66b8e090cc855e2f"`);
        await queryRunner.query(`ALTER TABLE "rds_enabled_cloudwatch_logs_exports_cloudwatch_logs_export" DROP CONSTRAINT "FK_8665c22521b74fcc1036760c572"`);
        await queryRunner.query(`ALTER TABLE "rds_domain_memberships_domain_membership" DROP CONSTRAINT "FK_1af07c6514ee027a2dc85ac79f8"`);
        await queryRunner.query(`ALTER TABLE "rds_domain_memberships_domain_membership" DROP CONSTRAINT "FK_5e9a0a3f9d6ef14aaac0cf9663e"`);
        await queryRunner.query(`ALTER TABLE "rds_db_parameter_groups_db_parameter_group_status" DROP CONSTRAINT "FK_4aa131803a030d058fe4abb7fed"`);
        await queryRunner.query(`ALTER TABLE "rds_db_parameter_groups_db_parameter_group_status" DROP CONSTRAINT "FK_388be0f10930095b8f207ef070f"`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_sup_act_str_mod_act_str_mod" DROP CONSTRAINT "FK_f3467c284d2ce88aabf61abd135"`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_sup_act_str_mod_act_str_mod" DROP CONSTRAINT "FK_c913ba69d17aa321078fda72506"`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_sup_eng_mod_sup_eng_mod" DROP CONSTRAINT "FK_3998b7d52519d19f2303e0b2ce8"`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_sup_eng_mod_sup_eng_mod" DROP CONSTRAINT "FK_704d81d4ab7a482a7fb39448887"`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_ava_pro_fea_pro_fea" DROP CONSTRAINT "FK_bb0adb88702053dd6f1cc7d9689"`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_ava_pro_fea_pro_fea" DROP CONSTRAINT "FK_19e4eab2447c349de981bcd3dc9"`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_ava_zon_ava_zon" DROP CONSTRAINT "FK_06b84b8cd688f4c5fccf4358c21"`);
        await queryRunner.query(`ALTER TABLE "ord_db_ins_opt_ava_zon_ava_zon" DROP CONSTRAINT "FK_f51aaa97cb0a59e1894dd10d804"`);
        await queryRunner.query(`ALTER TABLE "upgrade_target_supported_engine_modes_supported_engine_mode" DROP CONSTRAINT "FK_5eb731c791fd72e2159a82ff948"`);
        await queryRunner.query(`ALTER TABLE "upgrade_target_supported_engine_modes_supported_engine_mode" DROP CONSTRAINT "FK_8d9873989625cd727e2849357e6"`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_timezones_timezone" DROP CONSTRAINT "FK_8bf722a82544147511e5f305d0f"`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_timezones_timezone" DROP CONSTRAINT "FK_5e596e02a6f9cae013ef16ccb03"`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_feature_names_feature_name" DROP CONSTRAINT "FK_d6143d3a09a41fa2dd555631ffc"`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_feature_names_feature_name" DROP CONSTRAINT "FK_9b21e21f9cc5b3912ceb61ac999"`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_nchar_character_sets_character_set" DROP CONSTRAINT "FK_ddb19763885c9409cdd63e12013"`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_nchar_character_sets_character_set" DROP CONSTRAINT "FK_3fe9d74aca258c5be138cbd318c"`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_character_sets_character_set" DROP CONSTRAINT "FK_40ee09086af8e73dfb789cf4aea"`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_character_sets_character_set" DROP CONSTRAINT "FK_c75893914eaa6b126d86ea1107c"`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_engine_modes_supported_engine_mode" DROP CONSTRAINT "FK_bf981feb7226ab1eea1f8137e93"`);
        await queryRunner.query(`ALTER TABLE "engine_version_supported_engine_modes_supported_engine_mode" DROP CONSTRAINT "FK_5219b2e9e7239aedab4c0efd880"`);
        await queryRunner.query(`ALTER TABLE "engine_version_exportable_log_types_exportable_log_type" DROP CONSTRAINT "FK_20d6999924d3689ce9c6feba0bb"`);
        await queryRunner.query(`ALTER TABLE "engine_version_exportable_log_types_exportable_log_type" DROP CONSTRAINT "FK_213878cf8b7fe21a798590901e6"`);
        await queryRunner.query(`ALTER TABLE "engine_version_valid_upgrade_targets_upgrade_target" DROP CONSTRAINT "FK_3f6eada6a897f57e03afdca8b49"`);
        await queryRunner.query(`ALTER TABLE "engine_version_valid_upgrade_targets_upgrade_target" DROP CONSTRAINT "FK_0b9d53fadcfc2b156c0578e26ab"`);
        await queryRunner.query(`ALTER TABLE "rds" DROP CONSTRAINT "FK_dab66e009d8ba438e795c9f2105"`);
        await queryRunner.query(`ALTER TABLE "rds" DROP CONSTRAINT "FK_7a5a4239f36cb66f08e56ffcf1c"`);
        await queryRunner.query(`ALTER TABLE "rds" DROP CONSTRAINT "FK_8e3b0a8a106963b1b17af2bd674"`);
        await queryRunner.query(`ALTER TABLE "rds" DROP CONSTRAINT "FK_505a7144df2d71295aac1bf0da0"`);
        await queryRunner.query(`ALTER TABLE "rds" DROP CONSTRAINT "FK_f0c9a8ba920bd21d2f2833e1d92"`);
        await queryRunner.query(`ALTER TABLE "rds" DROP CONSTRAINT "FK_f78aee03934884ec12ed206c6ee"`);
        await queryRunner.query(`ALTER TABLE "rds" DROP CONSTRAINT "FK_88d7baba1011b1d780d4087e401"`);
        await queryRunner.query(`ALTER TABLE "orderable_db_instance_option" DROP CONSTRAINT "FK_46e53cc6bc7fcf5aec05a444ac7"`);
        await queryRunner.query(`ALTER TABLE "orderable_db_instance_option" DROP CONSTRAINT "FK_b2609a55c9361c6c05549bb3e22"`);
        await queryRunner.query(`ALTER TABLE "upgrade_target" DROP CONSTRAINT "FK_f72e551ae46bb42c1b7d5c0c958"`);
        await queryRunner.query(`ALTER TABLE "engine_version" DROP CONSTRAINT "FK_87600ab5ee44e3d1d2c7bb01083"`);
        await queryRunner.query(`ALTER TABLE "network_info" DROP COLUMN "ipv6_supported"`);
        await queryRunner.query(`ALTER TABLE "network_info" DROP COLUMN "ipv6_addresses_per_interface"`);
        await queryRunner.query(`ALTER TABLE "network_info" DROP COLUMN "ipv4_addresses_per_interface"`);
        await queryRunner.query(`ALTER TABLE "network_info" ADD "ipv6supported" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "network_info" ADD "ipv6addresses_per_interface" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "network_info" ADD "ipv4addresses_per_interface" integer NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_beb48b6f5416317665601f5ec2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dee88cf6b0fb66db5052dde9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8f22ea64822d21e101ba1d266"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1a95637fa3572dc302c5560d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8771bbe0783f3ff703bdb7e99"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f8d69062593d90e1d7a575463"`);
        await queryRunner.query(`DROP TABLE "rds_vpc_security_groups_security_group"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c8e70858e8f1e5d846414914e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2df06d9732e153c117aa5e22d6"`);
        await queryRunner.query(`DROP TABLE "rds_tags_tag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_568be2825b0cb4b0badc098c3b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_040989e476315840c5bc4f0c6d"`);
        await queryRunner.query(`DROP TABLE "rds_processor_features_processor_feature"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21d2baf09d1f84ca46f77c287a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46a3198cc9c5fc5c423422dfb7"`);
        await queryRunner.query(`DROP TABLE "rds_option_group_memberships_option_group_membership"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edb9b1dc35e66b8e090cc855e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8665c22521b74fcc1036760c57"`);
        await queryRunner.query(`DROP TABLE "rds_enabled_cloudwatch_logs_exports_cloudwatch_logs_export"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1af07c6514ee027a2dc85ac79f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e9a0a3f9d6ef14aaac0cf9663"`);
        await queryRunner.query(`DROP TABLE "rds_domain_memberships_domain_membership"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9edbd59b36dd67467f0f1fecfa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f6b4512583474990282b90635"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4aa131803a030d058fe4abb7fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_388be0f10930095b8f207ef070"`);
        await queryRunner.query(`DROP TABLE "rds_db_parameter_groups_db_parameter_group_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3467c284d2ce88aabf61abd13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c913ba69d17aa321078fda7250"`);
        await queryRunner.query(`DROP TABLE "ord_db_ins_opt_sup_act_str_mod_act_str_mod"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3998b7d52519d19f2303e0b2ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_704d81d4ab7a482a7fb3944888"`);
        await queryRunner.query(`DROP TABLE "ord_db_ins_opt_sup_eng_mod_sup_eng_mod"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb0adb88702053dd6f1cc7d968"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19e4eab2447c349de981bcd3dc"`);
        await queryRunner.query(`DROP TABLE "ord_db_ins_opt_ava_pro_fea_pro_fea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06b84b8cd688f4c5fccf4358c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f51aaa97cb0a59e1894dd10d80"`);
        await queryRunner.query(`DROP TABLE "ord_db_ins_opt_ava_zon_ava_zon"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5eb731c791fd72e2159a82ff94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d9873989625cd727e2849357e"`);
        await queryRunner.query(`DROP TABLE "upgrade_target_supported_engine_modes_supported_engine_mode"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bf722a82544147511e5f305d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e596e02a6f9cae013ef16ccb0"`);
        await queryRunner.query(`DROP TABLE "engine_version_supported_timezones_timezone"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6143d3a09a41fa2dd555631ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b21e21f9cc5b3912ceb61ac99"`);
        await queryRunner.query(`DROP TABLE "engine_version_supported_feature_names_feature_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddb19763885c9409cdd63e1201"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fe9d74aca258c5be138cbd318"`);
        await queryRunner.query(`DROP TABLE "engine_version_supported_nchar_character_sets_character_set"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40ee09086af8e73dfb789cf4ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c75893914eaa6b126d86ea1107"`);
        await queryRunner.query(`DROP TABLE "engine_version_supported_character_sets_character_set"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf981feb7226ab1eea1f8137e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5219b2e9e7239aedab4c0efd88"`);
        await queryRunner.query(`DROP TABLE "engine_version_supported_engine_modes_supported_engine_mode"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20d6999924d3689ce9c6feba0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_213878cf8b7fe21a798590901e"`);
        await queryRunner.query(`DROP TABLE "engine_version_exportable_log_types_exportable_log_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f6eada6a897f57e03afdca8b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b9d53fadcfc2b156c0578e26a"`);
        await queryRunner.query(`DROP TABLE "engine_version_valid_upgrade_targets_upgrade_target"`);
        await queryRunner.query(`DROP TABLE "rds"`);
        await queryRunner.query(`DROP TYPE "public"."rds_replica_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rds_activity_stream_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rds_storage_type_enum"`);
        await queryRunner.query(`DROP TABLE "endpoint"`);
        await queryRunner.query(`DROP TABLE "option_group_membership"`);
        await queryRunner.query(`DROP TABLE "domain_membership"`);
        await queryRunner.query(`DROP TABLE "orderable_db_instance_option"`);
        await queryRunner.query(`DROP TABLE "processor_feature"`);
        await queryRunner.query(`DROP TABLE "upgrade_target"`);
        await queryRunner.query(`DROP TABLE "engine_version"`);
        await queryRunner.query(`DROP TABLE "timezone"`);
        await queryRunner.query(`DROP TABLE "supported_engine_mode"`);
        await queryRunner.query(`DROP TABLE "feature_name"`);
        await queryRunner.query(`DROP TABLE "exportable_log_type"`);
        await queryRunner.query(`DROP TABLE "db_parameter_group_status"`);
        await queryRunner.query(`DROP TABLE "db_instance_class"`);
        await queryRunner.query(`DROP TABLE "cloudwatch_logs_export"`);
        await queryRunner.query(`DROP TABLE "character_set"`);
        await queryRunner.query(`DROP TABLE "activity_stream_mode"`);
        await queryRunner.query(`ALTER TYPE "public"."disk_info_disk_type_enum" RENAME TO "disk_info_type_enum"`);
        await queryRunner.query(`ALTER TABLE "disk_info" RENAME COLUMN "disk_type" TO "type"`);
    }

}
