name: Deploy to Staging

on:
  push:
    branches: [main]
    paths: ['src/**', 'test/**', 'package.json', 'yarn.lock', 'examples/**', '.github/workflows/staging/staging.yml']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Commit SHA
        required: false
        type: string

jobs:
  setup-build:
    runs-on: ubuntu-latest
    outputs:
      registry-image-tag: ${{ steps['set-registry-image-tag'].outputs['registry-image-tag'] }}
    steps:
      - id: set-registry-image-tag
        name: Set registry image tag
        run: |
          COMMIT_SHA=${{inputs.commit_sha}}
          echo "::set-output name=registry-image-tag::ghcr.io/iasql/iasql:$(echo ${COMMIT_SHA:-$GITHUB_SHA})"

  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - setup-build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.commit_sha}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ needs.setup-build.outputs.registry-image-tag }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - setup-build
      - build-and-push
    steps:
      - name: SSH into Staging and Deploy
        env:
          STAGING_PEM_B64: ${{ secrets.STAGING_PEM_B64 }}
          DOCKER_URL: ${{ needs.setup-build.outputs.registry-image-tag }}
        run: |
          echo $STAGING_PEM_B64 | base64 -d > staging.pem
          chmod 700 staging.pem
          # TODO: Figure out a secure way to log in to ghcr.io
          ssh -i staging.pem -o "StrictHostKeyChecking no" ubuntu@pg-staging.iasql.com "
            sudo apt update && sudo apt upgrade -y
            sudo docker pull $DOCKER_URL
            sudo docker container stop iasql
            sudo docker container rm iasql
            sudo docker run -d --env-file=.env -p 5432:5432 -v /iasqldb:/var/lib/postgresql/14 --name iasql $DOCKER_URL
            sudo docker image prune -af
          "
          rm staging.pem

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - deploy
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled

    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}