name: Build Docker image in different arch

on:
  push:
    branches: [main, build-arch]
    paths: ['Dockerfile', '.github/workflows/build-arch.yml']
  pull_request:
    branches: [main]
    paths: ['Dockerfile', '.github/workflows/build-arch.yml']

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo $GITHUB_SHA

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: ghcr.io/iasql/iasql:${{env.GITHUB_SHA}}

      # - name: Docker run
      #   run: |
      #     # Spin up IaSQL container and a postgres instance
      #     docker run -p 9876:9876 -p 5432:5432 -e IASQL_ENV=ci --name iasql ghcr.io/iasql/iasql:$GITHUB_SHA &
      #     while ! psql postgres://postgres:test@localhost:5432/iasql_metadata -b -q -c "SELECT iasql_engine_health()"; do sleep 1 && echo -n .; done;
