# This is a basic workflow to help you get started with Actions

name: DBDOC

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [release]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dbdocs
        run: |
          sudo npm install -g dbdocs
          sudo npm install -g @dbml/cli

      - name: Check dbdocs
        run: dbdocs

      - name: Start local iasql container
        run: |
          IASQL_ENV=ci docker-compose up --build --detach
          while ! curl --output /dev/null --silent --head --fail http://localhost:8088/health; do sleep 1 && echo -n .; done;

      - name: Run generation script
        run: ./src/scripts/dbdoc-ci.sh
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
          # no infrastructure changes so aws envs are irrelevant
          AWS_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
          DATABASE_URL: postgres://postgres:test@localhost:5432/iasql

      - name: Dump schema.prisma
        run: cat examples/ecs-fargate/prisma/infra/prisma/schema.prisma

      - name: Dump iasql.dbml
        run: cat examples/ecs-fargate/prisma/infra/prisma/dbml/iasql.dbml

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - update
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled

    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}