# This is a basic workflow to help you get started with Actions

name: DBDOC

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [release]
