name: Develop New Version

on:
  workflow_dispatch:
    inputs:
      next-version:
        required:  true
        description: 'Specify the version number of the next release'

jobs:
  drop-old-version:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Develop new version
        run: |
          git config --local user.email "iasql-bot@users.noreply.github.com"
          git config --local user.name "iasql-bot"
          yarn develop ${{ github.event.inputs.next-version }}
