name: Docker image change

on:
  push:
    branches: [main]
    paths: ['Dockerfile', '.github/workflows/tests-site.yml']
  pull_request:
    branches: [main]
    paths: ['Dockerfile', '.github/workflows/tests-site.yml']

jobs:
  run-container:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Start local iasql engine
        run: |
          docker build -t iasql:latest .
          docker run -p 5432:5432 -e IASQL_ENV=ci --name iasql iasql:latest &
          while ! psql postgres://postgres:test@localhost:5432/iasql_metadata -b -q -c "SELECT iasql_engine_health()"; do sleep 1 && echo -n .; done;
