name: Notify install time

on:
  push:
    branches: [notify-wf]
  pull_request:
    branches: [main]
    paths: ['src/**', 'package.json', 'yarn.lock']

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context.issue))
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })