on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# pushing releases to an empty public repo since this repo is private
name: Release CLI in iasql/releases

defaults:
  run:
    working-directory: ./cli

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate IaSQL tar.gz
      run: |
        cargo build --release
        cd ./target/release
        tar -czf /tmp/iasql-ubuntu.tar.gz iasql

    - name: Upload IaSQL zip
      uses: softprops/action-gh-release@v1
      with:
        # default GITHUB_TOKEN only has access to this repo so using @depombo's PAT
        # to push to alantech/iasql-releases
        token: ${{ secrets.GH_PAT }}
        repository: iasql/releases
        files: /tmp/iasql-ubuntu.tar.gz

    - name: Generate IaSQL Debian package
      run: |
        sudo apt install checkinstall -y
        iasqlversion=$(echo ${{github.ref}} | sed "s/refs\/tags\/v//")
        echo "Infrastructure as SQL (IaSQL) CLI client\n\n" | sudo checkinstall --install=no -D --pkgversion=${iasqlversion} --pkglicense=Proprietary --maintainer=hello@iasql.com --pkggroup="IaSQL" --nodoc --deldesc=yes --delspec=yes --backup=no
        cp ./cli_${iasqlversion}-1_amd64.deb /tmp/iasql_ubuntu_amd64.deb

    - name: Upload IaSQL Debian package
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GH_PAT }}
        repository: iasql/releases
        files: /tmp/iasql_ubuntu_amd64.deb

  windows:
    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate IaSQL zip
      run: |
        cargo build --release
        Compress-Archive -Path "$(Join-Path (Get-Location).Path '\\target\\release\\iasql.exe')" -DestinationPath "$(Join-Path (Get-Location).Path 'iasql-windows.zip')"

    - name: Upload IaSQL zip
      uses: softprops/action-gh-release@v1
      with:
        # default GITHUB_TOKEN only has access to this repo so using @depombo's PAT
        # to push to alantech/iasql-releases
        token: ${{ secrets.GH_PAT }}
        repository: iasql/releases
        files: D:\a\iasql\iasql\cli\iasql-windows.zip

  macos:
    runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate IaSQL tar.gz
      run: |
        cargo build --release
        cd ./target/release
        gtar -czf /tmp/iasql-macos.tar.gz iasql

    - name: Upload IaSQL tar.gz
      uses: softprops/action-gh-release@v1
      with:
        # default GITHUB_TOKEN only has access to this repo so using @depombo's PAT
        # to push to alantech/iasql-releases
        token: ${{ secrets.GH_PAT }}
        repository: iasql/releases
        files: /tmp/iasql-macos.tar.gz
