name: Publish Docker image

on:
  workflow_dispatch:
    version:
      description: 'Version for docker image'
    inputs:
      version:
        required: true
        description: 'Version for docker image'
  repository_dispatch:
    types: [release]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata labels for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: iasql/iasql

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: iasql/iasql:latest, iasql/iasql:${{ github.event.client_payload.version }}${{ github.event.client_payload.message.version }}${{ github.event.inputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - push_to_registry
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled

    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}