# Clean-up AWS accounts on a CRON Schedule
name: Clean AWS accounts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  # TODO: delete this before merge
  push:
    branches: [clean-test]
  # schedule:
  #   # Runs "daily at 6:15am UTC - 11:15pm PDT - 1:15am CDT - 8:15am CEST"
  #   # Github Actions have heavy load every start hour, so we wait 15 min to avoid delays in our jobs
  #   - cron: '15 6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        description: 'Optional region to delete'

jobs:
  setup-module-cleanup:
    runs-on: ubuntu-latest
    outputs:
      set-test-module-names: ${{ steps['set-test-module-names'].outputs['test-module-names'] }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - id: set-test-module-names
        name: Set modules tests names
        run: echo "::set-output name=test-module-names::$(npx jest **/modules/*ecs* --listTests --json | jq -c 'map(split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring)')"

  # Job by region since we pass the 256 job limit running them all at once
  # cleanup-ap:
  #   if: ${{ github.event.inputs.region == '' }}
  #   needs:
  #     - setup-module-cleanup
  #   # TODO: update branch before merge
  #   uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@clean-test
  #   with:
  #     modules: ${{ needs.setup-module-cleanup.outputs['set-test-module-names'] }}
  #     regions: "['ap-northeast-1', 'ap-northeast-2', 'ap-northeast-3', 'ap-south-1', 'ap-southeast-1', 'ap-southeast-2']"
  #   secrets: inherit

  cleanup-us:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    # TODO: update branch before merge
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@clean-test
    with:
      modules: ${{ needs.setup-module-cleanup.outputs['set-test-module-names'] }}
      regions: "['us-east-2', 'us-west-1', 'us-west-2']"
    secrets: inherit

  cleanup-sa_ca:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    # TODO: update branch before merge
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@clean-test
    with:
      modules: ${{ needs.setup-module-cleanup.outputs['set-test-module-names'] }}
      regions: "['sa-east-1', 'ca-central-1']"
    secrets: inherit

  cleanup-eu:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    # TODO: update branch before merge
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@clean-test
    with:
      modules: ${{ needs.setup-module-cleanup.outputs['set-test-module-names'] }}
      regions: "['eu-north-1', 'eu-west-1', 'eu-west-2', 'eu-west-3', 'eu-central-1']"
    secrets: inherit

  cleanup-custom:
    if: ${{ github.event.inputs.region != '' }}
    needs:
      - setup-module-cleanup
    # TODO: update branch before merge
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@clean-test
    with:
      modules: ${{ needs.setup-module-cleanup.outputs['set-test-module-names'] }}
      regions: ${{ format('[{0}]', github.event.inputs.region) }}
    secrets: inherit
