# Clean-up AWS accounts on a CRON Schedule
name: Clean AWS accounts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  schedule:
    # Runs "daily at 6:15am UTC - 11:15pm PDT - 1:15am CDT - 8:15am CEST"
    # Github Actions have heavy load every start hour, so we wait 15 min to avoid delays in our jobs
    - cron: '15 6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        description: 'Optional region to delete'
        required: false

jobs:
  setup-module-cleanup:
    runs-on: ubuntu-latest
    outputs:
      set-test-account-ids: ${{ steps['set-test-account-ids'].outputs['test-account-ids'] }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - id: set-test-account-ids
        name: Set modules tests names
        run: echo "::set-output name=test-account-ids::$(node -e "console.log(JSON.stringify([...Array(100)].map((_, i) => i.toString())))")

  # Job by region since we pass the 256 job limit running them all at once
  cleanup-ap-northeast-1:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: ap-northeast-1
      global: false
    secrets: inherit

  cleanup-ap-northeast-2:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: ap-northeast-2
      global: false
    secrets: inherit

  cleanup-ap-northeast-3:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: ap-northeast-3
      global: false
    secrets: inherit

  cleanup-ap-south-1:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: ap-south-1
      global: false
    secrets: inherit

  cleanup-ap-southeast-1:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: ap-southeast-1
      global: false
    secrets: inherit

  cleanup-ap-southeast-2:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: ap-southeast-2
      global: false
    secrets: inherit

  cleanup-us-east-2:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: us-east-2
      global: false
    secrets: inherit

  cleanup-us-west-1:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: us-west-1
      global: false
    secrets: inherit

  cleanup-us-west-2:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: us-west-2
      global: false
    secrets: inherit

  cleanup-sa_east-1:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: sa-east-1
      global: false
    secrets: inherit

  cleanup-ca-central-1:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: ca-central-1
      global: false
    secrets: inherit

  cleanup-eu-north-1:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: eu-north-1
      global: false
    secrets: inherit

  cleanup-eu-west-1:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: eu-west-1
      global: false
    secrets: inherit

  cleanup-eu-west-2:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: eu-west-2
      global: false
    secrets: inherit

  cleanup-eu-west-3:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: eu-west-3
      global: false
    secrets: inherit

  cleanup-eu-central-1:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: eu-central-1
      global: false
    secrets: inherit

  cleanup-global:
    if: ${{ github.event.inputs.region == '' }}
    needs:
      - setup-module-cleanup
      - cleanup-ap-northeast-1
      - cleanup-ap-northeast-2
      - cleanup-ap-northeast-3
      - cleanup-ap-south-1
      - cleanup-ap-southeast-1
      - cleanup-ap-southeast-2
      - cleanup-us-east-2
      - cleanup-us-west-1
      - cleanup-us-west-2
      - cleanup-sa_east-1
      - cleanup-ca-central-1
      - cleanup-eu-north-1
      - cleanup-eu-west-1
      - cleanup-eu-west-2
      - cleanup-eu-west-3
      - cleanup-eu-central-1
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: us-east-1
      global: true
    secrets: inherit

  cleanup-custom:
    if: ${{ github.event.inputs.region != '' }}
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: ${{ github.event.inputs.region }}
      global: false
    secrets: inherit

  cleanup-global-custom:
    if: ${{ github.event.inputs.region != '' }}
    needs:
      - setup-module-cleanup
      - cleanup-custom
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@main
    with:
      account_ids: ${{ needs.setup-module-cleanup.outputs['set-test-account-ids'] }}
      region: ${{ github.event.inputs.region }}
      global: true
    secrets: inherit

  notify:
      name: Discord Notification
      runs-on: ubuntu-latest
      needs: # make sure the notification is sent AFTER the jobs you want included have completed
        - cleanup-global
        - cleanup-global-custom
      if: ${{ always() }} # You always want to be notified: success, failure, or cancelled

      steps:
        - name: Notify
          uses: nobrayner/discord-webhook@v1
          with:
            github-token: ${{ secrets.github_token }}
            discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
