name: Clean-up AWS accounts on a CRON Schedule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  push:
    branches: [clean-test]
  # schedule:
  #   # Runs "daily at 6am UTC - 11pm PDT - 1am CDT - 8am CEST"
  #   - cron: '0 6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  # TODO: add region input
  workflow_dispatch:

jobs:
  setup-module-cleanup:
    runs-on: ubuntu-latest
    outputs:
      set-test-module-names: ${{ steps['set-test-module-names'].outputs['test-module-names'] }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - id: set-test-module-names
        name: Set modules tests names
        run: echo "::set-output name=test-module-names::$(npx jest **/modules/*ec2* --listTests --json | jq -c 'map(split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring)')"

  cleanup-1:
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@clean-test
    with:
      modules: ${{ needs.setup-module-cleanup.outputs['set-test-module-names'] }}
      regions: "['ap-northeast-1', 'ap-northeast-2', 'ap-northeast-3', 'ap-south-1', 'ap-southeast-1', 'ap-southeast-2', 'ca-central-1', 'eu-central-1']"
    secrets: inherit

  cleanup-2:
    needs:
      - setup-module-cleanup
    uses: iasql/iasql-engine/.github/workflows/module-cleanup.yml@clean-test
    with:
      modules: ${{ needs.setup-module-cleanup.outputs['set-test-module-names'] }}
      regions: "['eu-north-1', 'eu-west-1', 'eu-west-2', 'eu-west-3', 'sa-east-1', 'us-east-2', 'us-west-1', 'us-west-2']"
    secrets: inherit
