# TODO: Legacy workflow
name: 'Version: Release Newest'

on:
  workflow_dispatch:

jobs:
  release-latest-version:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Release latest version
        run: |
          git config --local user.email "iasql-bot@users.noreply.github.com"
          git config --local user.name "iasql-bot"
          yarn run version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Version For Doc Generation
        id: format-version
        run: |
          VERSION="$(jq -r '.version' package.json)"
          echo ::set-output name=version::${VERSION}

      - name: Emit for doc generation
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.GH_PAT }}
          event_type: release
          message: |
            {
              "version": "${{ steps.format-version.outputs.version }}"
            }
