name: WEB

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # https://auth0.com/docs/brand-and-customize/text-customization-new-universal-login
  a0-login-prompt:
    runs-on: ubuntu-latest
    steps:
    - name: Set Auth0 UI login prompt
      run: |
        curl \
        --request PUT \
        --url 'https://iasql.us.auth0.com/api/v2/prompts/login/custom-text/en' \
        --header 'authorization: Bearer ${{ secrets.A0_MANAGEMENT_API_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "login": {
            "title": "Login to IaSQL",
            "description": " ",
            "signupActionText": "Need an IaSQL account?",
            "signupActionLinkText": "Sign up"
          }
        }'

  a0-signup-prompt:
    runs-on: ubuntu-latest
    steps:
    - name: Set Auth0 UI signup prompt
      run: |
        curl \
        --request PUT \
        --url 'https://iasql.us.auth0.com/api/v2/prompts/signup/custom-text/en' \
        --header 'authorization: Bearer ${{ secrets.A0_MANAGEMENT_API_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "signup": {
            "title": "Sign Up to IaSQL",
            "description": " "
          }
        }'

  a0-branding-config:
    runs-on: ubuntu-latest
    steps:
    - name: Set Auth0 branding config
      run: |
        curl \
        --request PATCH \
        --url 'https://iasql.us.auth0.com/api/v2/branding' \
        --header 'authorization: Bearer ${{ secrets.A0_MANAGEMENT_API_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "colors": {
            "page_background": "#7090F5",
            "primary": "#304CA7"
          },
          "logo_url": "https://beta.iasql.com/img/logo.svg"
        }'
  
  a0-access-control:
    runs-on: ubuntu-latest
    steps:
    - name: Update IaSQL client app configuration
      run: |
        curl \
        --request PATCH \
        --url 'https://iasql.us.auth0.com/api/v2/clients/OLQAngfr1LnenTt6wmQOYKmzx1c1dSxg' \
        --header 'authorization: Bearer ${{ secrets.A0_MANAGEMENT_API_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
            "callbacks": [
              "http://localhost:3000/dashboard",
              "https://beta.iasql.com/dashboard"
            ],
            "allowed_logout_urls": [
              "http://localhost:3000",
              "https://*.iasql.com"
            ]
        }'

  a0-ui-template:
    runs-on: ubuntu-latest
    steps:
    - name: Set Auth0 UI template
      run: |
        curl \
        --request PATCH \
        --url 'https://iasql.us.auth0.com/api/v2/branding/templates/universal-login' \
        --header 'authorization: Bearer ${{ secrets.A0_MANAGEMENT_API_TOKEN }}' \
        --header 'content-type: application/html' \
        --data '<!DOCTYPE html>
          <html>
            <head>
              {%- auth0:head -%}
              <style>
                @import url("https://fonts.googleapis.com/css2?family=Gothic+A1&display=swap");
                body {
                  font-family: "Gothic A1" !important;
                }
              </style>
            </head>
            <body class="_widget-auto-layout">
              {%- auth0:widget -%}
            </body>
          </html>'