name: WEB

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # https://auth0.com/docs/brand-and-customize/text-customization-new-universal-login
  auth0-login-prompt:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: |
          --request PUT \
          --url 'https://iasql.us.auth0.com/api/v2/prompts/login/custom-text/en' \
          --header 'authorization: Bearer ${{ secrets.AUTH0_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "login": {
              "title": "Login to IaSQL",
              "description": " ",
              "signupActionLinkText": " ",
              "signupActionText": " "
            }
          }'
        # once we launch show singup again 
        # "signupActionLinkText": "Sign up",
        # "signupActionText": "Don't have an account?",

  auth0-signup-prompt:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: |
          --request PUT \
          --url 'https://iasql.us.auth0.com/api/v2/prompts/signup/custom-text/en'
          --header 'authorization: Bearer ${{ secrets.AUTH0_TOKEN }}'
          --header 'content-type: application/json'
          --data '{
            "signup": {
              "title": "Sign Up to IaSQL",
              "description": " "
            }
          }'

  auth0-branding-config:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: |
          --request PATCH \
          --url 'https://iasql.us.auth0.com/api/v2/branding' \
          --header 'authorization: Bearer ${{ secrets.AUTH0_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "colors": {
              "page_background": "#7090F5",
              "primary": "#304CA7"
            },
            "logo_url": "https://beta.iasql.com/img/logo.svg"
          }'
  
  auth0-ui-template:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: |
          --request PATCH \
          --url 'https://iasql.us.auth0.com/api/v2/branding/templates/universal-login' \
          --header 'authorization: Bearer ${{ secrets.AUTH0_TOKEN }}' \
          --header 'content-type: application/html' \
          --data '<!DOCTYPE html>
            <html>
              <head>
                {%- auth0:head -%}
                <style>
                  @import url("https://fonts.googleapis.com/css2?family=Gothic+A1&display=swap");
                  body {
                    font-family: "Gothic A1" !important;
                  }
                </style>
              </head>
              <body class="_widget-auto-layout">
                {%- auth0:widget -%}
              </body>
            </html>'

  publish-docusaurus:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          cd web
          npm install 
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: web/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}